apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: countly-observability

resources:
# Base configuration
- ../../base
# Local observability stack components
- loki-stack.yaml
- prometheus-stack.yaml
- grafana.yaml
- tempo-stack.yaml
- pyroscope-stack.yaml

configMapGenerator:
# Override base observability config with local endpoints
- name: observability-config
  behavior: replace
  envs:
  - configs/observability.env
# Grafana configuration
- name: grafana-config
  envs:
  - configs/grafana.env
# Grafana dashboards
- name: grafana-dashboards
  files:
  - dashboards/countly-overview.json
  - dashboards/countly-traces.json
  options:
    labels:
      grafana_dashboard: "1"

# No auth needed for local stack
secretGenerator:
- name: observability-auth
  behavior: replace
  literals:
  - PROMETHEUS_BEARER_TOKEN=""
  - LOKI_BEARER_TOKEN=""
  - TEMPO_AUTH_HEADER=""
  - PYROSCOPE_AUTH_HEADER=""

patches:
# Replace Alloy config with full configuration
- path: alloy-config-patch.yaml
  target:
    kind: ConfigMap
    name: alloy-config
    namespace: countly-observability

# Replace Alloy ConfigMap with generated name
replacements:
- source:
    kind: ConfigMap
    name: alloy-config
    fieldPath: metadata.name
  targets:
  - select:
      kind: DaemonSet
      name: alloy
    fieldPaths:
    - spec.template.spec.volumes.[name=config].configMap.name