apiVersion: v1
kind: ConfigMap
metadata:
  name: pyroscope-config
  namespace: countly-observability
data:
  config.yaml: |
    # Minimal Pyroscope configuration for v1.14.0
    target: all
    
    server:
      http_listen_port: 4040
      log_level: info
    
    pyroscopedb:
      data_path: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pyroscope-data
  namespace: countly-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyroscope
  namespace: countly-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pyroscope
  template:
    metadata:
      labels:
        app: pyroscope
    spec:
      securityContext:
        fsGroup: 10001
      initContainers:
      - name: init-data-dir
        image: busybox:1.35
        command: ['sh', '-c', 'chown -R 10001:10001 /data && chmod -R 755 /data']
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          runAsUser: 0
      containers:
      - name: pyroscope
        image: grafana/pyroscope:1.14.0
        # Updated to latest version 1.14.0
        # changelog: https://raw.githubusercontent.com/grafana/pyroscope/refs/heads/main/CHANGELOG.md
        args:
          - -config.file=/etc/pyroscope/config.yaml
          - -target=all
        ports:
        - containerPort: 4040
          name: http
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          runAsNonRoot: true
        volumeMounts:
        - name: config
          mountPath: /etc/pyroscope
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: 256Mi
            cpu: 100m
          limits:
            memory: 1Gi
            cpu: 1000m
      volumes:
      - name: config
        configMap:
          name: pyroscope-config
      - name: data
        persistentVolumeClaim:
          claimName: pyroscope-data

---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope
  namespace: countly-observability
spec:
  selector:
    app: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: 4040