export default {
	LOGO: '[data-test-id=login-logo]',
	LANGUAGE: '[data-test-id=login-active-lang]',
	SIGN_IN_LABEL: '[data-test-id=login-sign-in]',
	USERNAME_LABEL: '[data-test-id= login-username-label]',
	USERNAME: '[data-test-id= login-username]',
	PASSWORD_LABEL: '[data-test-id= login-password-label]',
	PASSWORD: '[data-test-id= login-password]',
	LOGIN_BUTTON: '[data-test-id= login-submit-button]',
	FORGOT_PASSWORD_LINK: '[data-test-id=login-forgot-password]',
	FOOTER: '[data-test-id=login-footer]',
	USERNAME_ERROR_MESSAGE: '[id=username-error]',
	NOTIFICATION_IMAGE: '[id=notification-image]',
	FAILED_MESSAGE: '[id=message]',
}
