export default {
	LOGO: 'login-logo',
	LANGUAGE: 'login-active-lang',
	SIGN_IN_LABEL: 'login-sign-in',
	USERNAME_LABEL: 'login-username-label',
	USERNAME: 'login-username',
	PASSWORD_LABEL: 'login-password-label',
	PASSWORD: 'login-password',
	LOGIN_BUTTON: 'login-submit-button',
	FORGOT_PASSWORD_LINK: 'login-forgot-password',
	FOOTER: 'login-footer',
	USERNAME_ERROR_MESSAGE: '#username-error',
	NOTIFICATION_IMAGE: '#notification-image',
	FAILED_MESSAGE: '#message',
}
