export default {
    SIDEBAR: 'dashboard-sidebar',
    SIDEBAR_MENU_OPTIONS_BAR: 'sidebar-menu-options',
    SIDEBAR_MAINMENU_APP_NAME: 'sidebar-mainmenu-app-name',
    SIDEBAR_MAINMENU_APP_TYPE: 'sidebar-mainmenu-app-type',
    SIDEBAR_MENU_OPTIONS: {
        MAIN_MENU: 'sidebar-menuoptions-analytics',
        DASHBOARDS: 'sidebar-menuoptions-dashboards',
        MANAGEMENT: 'sidebar-menuoptions-management',
        REPORT_MANAGER: 'sidebar-menuoptions-reportmanager',
        HELP_CENTER: 'sidebar-menu-helpcenter',
        MY_PROFILE: 'sidebar-menuoptions-myprofile',
        LANGUAGE: 'language-menu',
        TOGGLE: 'sidebar-menuoptions-toogleleft'
    },

    SIDEBAR_MAIN_MENU_OPTIONS: {
        APP: 'sidebar-mainmenu-app',
        APP_IMAGE: 'sidebar-mainmenu-app-image',
        APP_NAME: 'sidebar-mainmenu-app-name',
        HOME: 'sidebar-mainmenu-overview',
        ANALYTICS: 'sidebar-mainmenu-menutitle-sidebar-analytics-el-collapse-item-label',
        ANALYTICS_ACTIVE_ARROW: '[data-test-id=sidebar-mainmenu-menutitle-sidebar-analytics-el-collapse-item-icon-right]' + '.is-active',
        ANALYTICS_LIST: {
            VISITOR_ANALYTICS: 'sidebar-mainmenu-subitem-analytics-users',
            VISITOR_LOYALTY: 'sidebar-mainmenu-subitem-analytics-loyalty',
            SESSION_ANALYTICS: 'sidebar-mainmenu-subitem-analytics-sessions',
            PAGE_VIEWS: 'sidebar-mainmenu-subitem-analytics-views',
            HEATMAPS: 'sidebar-mainmenu-subitem-heatmaps',
            ACQUISITION: 'sidebar-mainmenu-subitem-analytics-acquisition',
            TECHNOLOGY: 'sidebar-mainmenu-subitem-analytics-technology',
            GEO: 'sidebar-mainmenu-subitem-analytics-geo',
        },
        RETENTION: 'sidebar-mainmenu-url-retention',
        EVENTS: 'sidebar-mainmenu-menutitle-sidebar-events-el-collapse-item-label',
        EVENTS_LIST: {
            OVERVIEW: 'sidebar-mainmenu-subitem-events-overview',
            ALL_EVENTS: 'sidebar-mainmenu-subitem-all-events',
        },
        REVENUE: 'sidebar-mainmenu-revenue',
        VISITOR_PROFILES: 'sidebar-mainmenu-profiles',
        COHORTS: 'sidebar-mainmenu-cohorts',
        FUNNELS: 'sidebar-mainmenu-funnels',
        FLOWS: 'sidebar-mainmenu-flows',
        DRILL: 'sidebar-mainmenu-drill',
        FORMULAS: 'sidebar-mainmenu-formulas',
        FEEDBACK: 'sidebar-mainmenu-menutitle-sidebar-feedback-el-collapse-item-label',
        FEEDBACK_ACTIVE_ARROW: '[data-test-id=sidebar-mainmenu-menutitle-sidebar-feedback-el-collapse-item-icon-right]' + '.is-active',
        FEEDBACK_LIST: {
            SURVEYS: 'sidebar-mainmenu-submenu-ias',
            NPS: 'sidebar-mainmenu-submenu-nps',
            RATINGS: 'sidebar-mainmenu-subitem-star-rating',
        },
        ERRORS: 'sidebar-mainmenu-menutitle-crashes-title-el-collapse-item-label',
        ERRORS_LIST: {
            OVERVIEW: 'sidebar-mainmenu-submenu-crash',
            MANAGE_SYMBOLS: 'sidebar-mainmenu-submenu-symbols',
        },
        PERFORMANCE: 'sidebar-mainmenu-performance-monitoring',
        REMOTE_CONFIG: 'sidebar-mainmenu-remote-config',
        AB_TESTING: 'sidebar-mainmenu-ab-testing',
        UTILITIES: 'sidebar-mainmenu-menutitle-sidebar-utilities-el-collapse-item-label',
        UTILITIES_ACTIVE_ARROW: '[data-test-id=sidebar-mainmenu-menutitle-sidebar-utilities-el-collapse-item-icon-right]' + '.is-active',
        UTILITIES_LIST: {
            DATA_MANAGER: 'sidebar-mainmenu-subitem-data-manager',
            DATA_POPULATOR: 'sidebar-mainmenu-submenu-populate',
            CONFIG_TRANSFER: 'sidebar-mainmenu-submenu-export',
            INCOMING_DATA_LOGS: 'sidebar-mainmenu-submenu-logger',
            SDK_MANAGER: 'sidebar-mainmenu-submenu-sdk',
            COMPLIANCE_HUB: 'sidebar-mainmenu-submenu-compliance',
            SYMBOLICATION_LOGS: 'sidebar-mainmenu-submenu-symbol_jobs',
            FILTERING_LOGS: 'sidebar-mainmenu-submenu-blocks',
        },
        VERSION: 'sidebar-menu-version'
    },
};
