FROM node:14.20.0-bullseye-slim

ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,times-of-day,compliance-hub,alerts,onboarding,consolidate,remote-config,hooks,dashboards
# Enterprise Edition:
#ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,drill,funnels,retention_segments,flows,cohorts,surveys,remote-config,ab-testing,formulas,activity-map,concurrent_users,revenue,logger,systemlogs,populator,reports,crashes,push,geo,block,users,star-rating,slipping-away-users,compare,server-stats,assistant,dbviewer,crash_symbolication,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,active_users,performance-monitoring,config-transfer,consolidate,data-manager,hooks,dashboards,heatmaps

EXPOSE 6001
HEALTHCHECK --start-period=400s CMD curl --fail http://localhost:6001/ping || exit 1

USER root

# Core dependencies
## Tini
ENV COUNTLY_CONTAINER="frontend" \
	COUNTLY_DEFAULT_PLUGINS="${COUNTLY_PLUGINS}" \
	COUNTLY_CONFIG_FRONTEND_WEB_HOST="0.0.0.0" \
	TINI_VERSION="0.18.0"

WORKDIR /opt/countly
COPY . .

# install required dependencies which slim image doesn't have
RUN apt-get update && \
    apt-get install -y apt-transport-https curl wget git python3 python2 make gcc g++ unzip && \
    ln -s /usr/bin/python2.7 /usr/bin/python

RUN curl -s -L -o /tmp/tini.deb "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.deb" && \
	dpkg -i /tmp/tini.deb && \
	\
	# modify standard distribution
	apt-get update && apt-get install -y sqlite3 && \
	./bin/docker/modify.sh && \
	\
	# preinstall
	cp -n ./api/config.sample.js ./api/config.js && \
	cp -n ./frontend/express/config.sample.js ./frontend/express/config.js && \
	cp -n ./frontend/express/public/javascripts/countly/countly.config.sample.js ./frontend/express/public/javascripts/countly/countly.config.js && \
	HOME=/tmp npm install --unsafe-perm=true --allow-root && \
	HOME=/tmp npm install argon2 --build-from-source --unsafe-perm=true --allow-root && \
	./bin/docker/preinstall.sh && \
	bash /opt/countly/bin/scripts/detect.init.sh && \
	countly update sdk-web && \
	\
	# cleanup & chown
	npm remove -y --no-save mocha nyc should supertest puppeteer && \
	apt-get remove -y git gcc g++ make automake autoconf libtool pkg-config unzip sqlite3 && \
	apt-get autoremove -y && \
	apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
	rm -rf test /tmp/* /tmp/.??* /var/tmp/* /var/tmp/.??* /var/log/* /root/.npm && \
	\
	# temporary to remove npm bug message
	mkdir /.npm && chown -R 1001:0 /.npm && \
	\
	chown -R 1001:0 /opt/countly && \
	chmod -R g=u /opt/countly


USER 1001:0

ENTRYPOINT ["/usr/bin/tini", "-v", "--"]

CMD ["/opt/countly/bin/docker/cmd.sh"]
