FROM centos/nodejs-10-centos7

ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,times-of-day,compliance-hub,video-intelligence-monetization,alerts,onboarding
# Enterprise Edition:
#ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,drill,funnels,concurrent_users,retention_segments,revenue,logger,systemlogs,populator,reports,crashes,push,block,restrict,users,geo,star-rating,slipping-away-users,compare,server-stats,dashboards,assistant,flows,dbviewer,cohorts,crash_symbolication,crashes-jira,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,remote-config,formulas,ab-testing,active_users,performance-monitoring

EXPOSE 6001
HEALTHCHECK --start-period=120s CMD curl --fail http://localhost:6001/ping || exit 1

USER root

# Core dependencies
## Tini
ENV COUNTLY_CONTAINER="frontend" \
	COUNTLY_DEFAULT_PLUGINS="${COUNTLY_PLUGINS}" \
	COUNTLY_CONFIG_FRONTEND_WEB_HOST="0.0.0.0" \
	TINI_VERSION="0.18.0" \
	PATH="/opt/rh/rh-nodejs10/root/usr/bin:${PATH}"

WORKDIR /opt/countly
COPY . .

RUN curl -s -L -o /tmp/tini.rpm "https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.rpm" && \
	rpm -i /tmp/tini.rpm && \
	# modify standard distribution
	./bin/docker/modify.sh && \
	\
	# preinstall
	cp -n ./frontend/express/public/javascripts/countly/countly.config.sample.js ./frontend/express/public/javascripts/countly/countly.config.js && \
	cp -n ./frontend/express/config.sample.js ./frontend/express/config.js && \
	cp -n ./api/config.sample.js ./api/config.js && \
	HOME=/tmp npm install --unsafe-perm=true --allow-root && \
	HOME=/tmp npm install argon2 --build-from-source --unsafe-perm=true --allow-root && \
	./bin/docker/preinstall.sh && \
	bash /opt/countly/bin/scripts/detect.init.sh && \
	countly update sdk-web && \
	\
	# cleanup & chown
	npm remove -y mocha nyc should supertest puppeteer && \
	rm -rf /opt/app-root/src/.npm && \
	yum remove -y git gcc make automake autoconf makedepend zlib-devel libxml2-devel python-setuptools openssl-devel devtoolset-7-gcc devtoolset-7-libstdc++-devel python36-devel centos-release-scl devtoolset-7-gcc-c++ && \
	yum -y autoremove && \
	yum clean all && \
	rm -rf /tmp/* /tmp/.??* /var/tmp/* /var/tmp/.??* /var/log/* && \
	chown -R 1001:0 /opt/countly && \
	chmod -R g=u /opt/countly && \
	\
	bash ./bin/scripts/detect.init.sh && \
	./bin/commands/countly.sh update sdk-web


USER 1001:0

ENTRYPOINT ["/usr/bin/tini", "-v", "--"]

CMD ["/opt/countly/bin/docker/cmd.sh"]
