FROM centos/nodejs-8-centos7

ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,enterpriseinfo,logger,systemlogs,populator,reports,crashes,push,star-rating,slipping-away-users,compare,server-stats,dbviewer,assistant,times-of-day,compliance-hub,video-intelligence-monetization,alerts,onboarding
# Enterprise Edition:
#ARG COUNTLY_PLUGINS=mobile,web,desktop,plugins,density,locale,browser,sources,views,drill,funnels,concurrent_users,retention_segments,revenue,logger,systemlogs,populator,reports,crashes,push,block,restrict,users,geo,star-rating,slipping-away-users,compare,server-stats,dashboards,assistant,flows,dbviewer,cohorts,crash_symbolication,crashes-jira,groups,white-labeling,alerts,times-of-day,compliance-hub,onboarding,remote-config,formulas,ab-testing

USER root

# Core dependencies
## Tini
ENV TINI_VERSION 0.18.0
ADD https://github.com/krallin/tini/releases/download/v${TINI_VERSION}/tini_${TINI_VERSION}.rpm /tmp/tini.rpm
RUN rpm -i /tmp/tini.rpm

ENTRYPOINT ["/usr/bin/tini", "-v", "--"]

RUN yum -y install sendmail

# Setup Countly
ENV COUNTLY_CONTAINER="frontend"
ENV COUNTLY_DEFAULT_PLUGINS="${COUNTLY_PLUGINS}"
ENV COUNTLY_CONFIG_FRONTEND_WEB_HOST="0.0.0.0"

## The files
RUN mkdir /opt/countly && chown 1001:0 /opt/countly
USER 1001:0
ENV PATH="/opt/rh/rh-nodejs8/root/usr/bin:${PATH}"
WORKDIR /opt/countly
COPY --chown=1001:0 . .
HEALTHCHECK --start-period=120s CMD curl --fail http://localhost:6001/ping || exit 1

RUN cp -n frontend/express/public/javascripts/countly/countly.config.sample.js frontend/express/public/javascripts/countly/countly.config.js && \
	cp -n frontend/express/config.sample.js frontend/express/config.js && \
	cp -n api/config.sample.js api/config.js && \
	HOME=/tmp npm install && \
	./bin/docker/preinstall.sh

USER root

RUN ./bin/docker/modify.sh && \
	chown -R 1001:0 /opt/countly && \
	bash /opt/countly/bin/scripts/detect.init.sh && \
	yum remove -y git gcc make automake autoconf makedepend zlib-devel libxml2-devel openssl-devel && \
	yum clean all && \
	rm -rf /tmp/* /var/tmp/*

USER 1001:0
RUN countly update sdk-web
CMD ["/opt/countly/bin/docker/cmd.sh"]