export default {
	PAGE_TITLE: 'ratings-header-title',
	PAGE_TITLE_TOOLTIP: 'ratings-header-tooltip',
	TAB_RATINGS: 'tab-ratings-tab-ratings-title',
	TAB_RATING_WIDGETS: 'tab-ratings-tab-rating-widgets-title',
	RESULTS_FOR_LABEL: 'ratings-result-for-label',
	FILTER_PARAMETERS_COMBOBOX: 'ratings-filter-parameters-dropdown-pseudo-input-label',
	FILTER_DATE_PICKER: 'ratings-date-range-select-dropdown-pseudo-input-label',
	TOTAL_RATINGS_LABEL: 'metric-card-ratings-total-ratings-column-label',
	TOTAL_RATINGS_TOOLTIP: 'metric-card-ratings-total-ratings-column-tooltip',
	TOTAL_RATINGS_NUMBER_LABEL: 'metric-card-ratings-total-ratings-column-number',
	AVERAGE_RATINGS_SCORE_LABEL: 'metric-card-ratings-average-ratings-score-column-label',
	AVERAGE_RATINGS_SCORE_TOOLTIP: 'metric-card-ratings-average-ratings-score-column-tooltip',
	AVERAGE_RATINGS_SCORE_NUMBER_LABEL: 'metric-card-ratings-average-ratings-score-column-number',
    EMPTY_CHART_ICON: 'ratings-chart-empty-logo',
    EMPTY_CHART_TITLE: 'ratings-chart-empty-title',
    EMPTY_CHART_SUBTITLE: 'ratings-chart-empty-subtitle',
}
