apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-clickhouse-updater
  namespace: countly
spec:
  template:
    spec:
      containers:
      - name: countly-clickhouse-updater
        envFrom:
        - configMapRef:
            name: observability-config-otlp
        env:
        - name: OTEL_SERVICE_NAME
          value: "countly-clickhouse-updater"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=countly,deployment.environment=production"
        - name: NODE_OPTIONS
          value: "$(NODE_OPTIONS) --require=/opt/countly/api/utils/otel.js"
