apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-aggregator
  namespace: countly
spec:
  template:
    spec:
      containers:
      - name: countly-aggregator
        envFrom:
        - configMapRef:
            name: observability-config-otlp
        env:
        - name: OTEL_SERVICE_NAME
          value: "countly-aggregator"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=countly,deployment.environment=production"
