export default {
    PAGE_TITLE: 'header-title',
    BUTTON_CUSTOMIZE: 'button-home-customize',
    BUTTON_MORE: 'cly-more-options-test-id-more-option-button',
    BUTTON_MORE_DOWNLOAD_ITEM: 'button-item-download',

    TOP_EVENTS: {
        LABEL: 'label-top-events-by-count-in-the-last-30-days',
        GO_TO_EVENTS_LINK: 'link-go-to-events',
        GO_TO_EVENTS_LINK_ARROW: 'link-arrow-go-to-events',
        EMPTY_CARD_BOX: 'empty-card-top-events-by-count-in-the-last-30-days',
        EMPTY_CARD_BOX_LABEL: 'empty-card-label-top-events-by-count-in-the-last-30-days',

        FIRST_COLUMN: 'metric-card-events-index-0-column',
        FIRST_COLUMN_LABEL: 'metric-card-events-index-0-column-label',
        FIRST_COLUMN_NUMBER: 'metric-card-events-index-0-column-number',
        FIRST_COLUMN_ARROW_ICON: 'metric-card-events-index-0-coloumn-trend-arrow-icon',
        FIRST_COLUMN_TREND_NUMBER: 'metric-card-events-index-0-coloumn-trend-desc',

        SECOND_COLUMN: 'metric-card-events-index-1-column',
        SECOND_COLUMN_LABEL: 'metric-card-events-index-1-column-label',
        SECOND_COLUMN_NUMBER: 'metric-card-events-index-1-column-number',
        SECOND_COLUMN_ARROW_ICON: 'metric-card-events-index-1-coloumn-trend-arrow-icon',
        SECOND_COLUMN_TREND_NUMBER: 'metric-card-events-index-1-coloumn-trend-desc',

        THIRD_COLUMN: 'metric-card-events-index-2-column',
        THIRD_COLUMN_LABEL: 'metric-card-events-index-2-column-label',
        THIRD_COLUMN_NUMBER: 'metric-card-events-index-2-column-number',
        THIRD_COLUMN_ARROW_ICON: 'metric-card-events-index-2-coloumn-trend-arrow-icon',
        THIRD_COLUMN_TREND_NUMBER: 'metric-card-events-index-2-coloumn-trend-desc',

        FOURTH_COLUMN: 'metric-card-events-index-3-column',
        FOURTH_COLUMN_LABEL: 'metric-card-events-index-3-column-label',
        FOURTH_COLUMN_NUMBER: 'metric-card-events-index-3-column-number',
        FOURTH_COLUMN_ARROW_ICON: 'metric-card-events-index-3-coloumn-arrow-icon',
        FOURTH_COLUMN_TREND_NUMBER: 'metric-card-events-index-3-coloumn-trend-desc',

        FIFTH_COLUMN: 'metric-card-events-index-4-column',
        FIFTH_COLUMN_LABEL: 'metric-card-events-index-4-column-label',
        FIFTH_COLUMN_NUMBER: 'metric-card-events-index-4-column-number',
        FIFTH_COLUMN_ARROW_ICON: 'metric-card-events-index-4-coloumn-trend-arrow-icon',
        FIFTH_COLUMN_TREND_NUMBER: 'metric-card-events-index-4-coloumn-trend-desc',
    },

    AUDIENCE: {
        DATE_PICKER: 'cly-datepicker-test-id-pseudo-input-label',
        LABEL: 'widget-label-audience',
        TOOLTIP: 'widget-tooltip-audience',
        GO_TO_SESSIONS_LINK: 'widget-link-go-to-sessions',
        GO_TO_SESSIONS_LINK_ARROW: 'widget-arrow-go-to-sessions',

        TOTAL_SESSIONS_TAB_BOX: 'tab-box-center-total-sessions',
        TOTAL_SESSIONS_LABEL: 'tab-box-label-total-sessions',
        TOTAL_SESSIONS_TOOLTIP: 'tab-box-tooltip-total-sessions',
        TOTAL_SESSIONS_NUMBER: 'tab-box-center-item-number-total-sessions',
        TOTAL_SESSIONS_TREND_ICON: 'tab-box-center-item-trend-icon-total-sessions',
        TOTAL_SESSIONS_TREND_VALUE: 'tab-box-center-item-trend-value-total-sessions',
        TOTAL_SESSIONS_CHART: 'tab-box-chart-total-sessions',

        NEW_SESSIONS_TAB_BOX: 'tab-box-new-sessions',
        NEW_SESSIONS_LABEL: 'tab-box-label-new-sessions',
        NEW_SESSIONS_TOOLTIP: 'tab-box-tooltip-new-sessions',
        NEW_SESSIONS_NUMBER: 'tab-box-center-item-number-new-sessions',
        NEW_SESSIONS_TREND_ICON: 'tab-box-center-item-trend-icon-new-sessions',
        NEW_SESSIONS_TREND_VALUE: 'tab-box-center-item-trend-value-new-sessions',
        NEW_SESSIONS_CHART: 'tab-box-chart-new-sessions',

        TIME_SPENT_TAB_BOX: 'tab-box-time-spent',
        TIME_SPENT_LABEL: 'tab-box-label-time-spent',
        TIME_SPENT_TOOLTIP: 'tab-box-tooltip-time-spent',
        TIME_SPENT_NUMBER: 'tab-box-center-item-number-time-spent',
        TIME_SPENT_TREND_ICON: 'tab-box-center-item-trend-icon-time-spent',
        TIME_SPENT_TREND_VALUE: 'tab-box-center-item-trend-value-time-spent',
        TIME_SPENT_CHART: 'tab-box-chart-time-spent',

        AVG_SESSION_DURATION_TAB_BOX: 'tab-box-avg-session-duration',
        AVG_SESSION_DURATION_LABEL: 'tab-box-label-avg-session-duration',
        AVG_SESSION_DURATION_TOOLTIP: 'tab-box-tooltip-avg-session-duration',
        AVG_SESSION_DURATION_NUMBER: 'tab-box-center-item-number-avg-session-duration',
        AVG_SESSION_DURATION_TREND_ICON: 'tab-box-center-item-trend-icon-avg-session-duration',
        AVG_SESSION_DURATION_TREND_VALUE: 'tab-box-center-item-trend-value-avg-session-duration',
        AVG_SESSION_DURATION_CHART: 'tab-box-chart-avg-session-duration',

        AVG_REQUESTS_RECEIVED_TAB_BOX: 'tab-box-avg-requests-received',
        AVG_REQUESTS_RECEIVED_LABEL: 'tab-box-label-avg-requests-received',
        AVG_REQUESTS_RECEIVED_TOOLTIP: 'tab-box-tooltip-avg-requests-received',
        AVG_REQUESTS_RECEIVED_NUMBER: 'tab-box-center-item-number-avg-requests-received',
        AVG_REQUESTS_RECEIVED_TREND_ICON: 'tab-box-center-item-trend-icon-avg-requests-received',
        AVG_REQUESTS_RECEIVED_TREND_VALUE: 'tab-box-center-item-trend-value-avg-requests-received',
        AVG_REQUESTS_RECEIVED_CHART: 'tab-box-chart-avg-requests-received',

        CHART_TYPE_SELECT_COMBOBOX: 'total-sessions-select-input',
        CHART_TYPE_SELECT_ICON: 'total-sessions-select-icon',
        CHART_TYPE_SELECT_LABEL: 'total-sessions-chart-type-label',
        CHART_TYPE_SELECT_ITEM_LINE_CHART: 'total-sessions-chart-type-toggle-wrapper-el-option-line',
        CHART_TYPE_SELECT_ITEM_LINE_CHART_TEXT: 'total-sessions-chart-type-toggle-wrapper-el-option-line-text',
        CHART_TYPE_SELECT_ITEM_BAR: 'total-sessions-chart-type-toggle-wrapper-el-option-bar',
        CHART_TYPE_SELECT_ITEM_BAR_TEXT: 'total-sessions-chart-type-toggle-wrapper-el-option-bar-text',
        MORE_OPTION_BUTTON: 'total-sessions-cly-chart-more-dropdown-more-option-button',
        MORE_OPTION_BUTTON_ITEM_DOWNLOAD: 'total-sessions-download-button',
        MORE_OPTION_BUTTON_ITEM_ZOOM_IN: 'total-sessions-more-zoom-button',
        CHART: 'tab-box-chart-total-sessions'
    },

    SOURCES: {
        LABEL: 'widget-label-sources',
        TOOLTIP: 'widget-tooltip-sources',
        GO_TO_ACQUISITION_LINK: 'widget-link-go-to-acquisition',
        GO_TO_ACQUISITION_LINK_ARROW: 'widget-arrow-go-to-acquisition',
        EMPTY_CARD_BOX: 'sources-wrapper-empty-card',
        EMPTY_CARD_BOX_LABEL: 'sources-wrapper-empty-card-label',

        FIRST_COLUMN: 'metric-card-sources-index-0-column',
        FIRST_COLUMN_LABEL: 'metric-card-sources-index-0-column-label',
        FIRST_COLUMN_TOOLTIP: 'metric-card-sources-index-0-column-tooltip',
        FIRST_COLUMN_NUMBER: 'metric-card-sources-index-0-column-number',
        FIRST_COLUMN_PROGRESS_BAR: 'el-progress-metric-card-sources-index-0-column',

        SECOND_COLUMN: 'metric-card-sources-index-1-column',
        SECOND_COLUMN_LABEL: 'metric-card-sources-index-1-column-label',
        SECOND_COLUMN_TOOLTIP: 'metric-card-sources-index-1-column-tooltip',
        SECOND_COLUMN_NUMBER: 'metric-card-sources-index-1-column-number',
        SECOND_COLUMN_PROGRESS_BAR: 'el-progress-metric-card-sources-index-1-column',

        THIRD_COLUMN: 'metric-card-sources-index-2-column',
        THIRD_COLUMN_LABEL: 'metric-card-sources-index-2-column-label',
        THIRD_COLUMN_TOOLTIP: 'metric-card-sources-index-2-column-tooltip',
        THIRD_COLUMN_NUMBER: 'metric-card-sources-index-2-column-number',
        THIRD_COLUMN_PROGRESS_BAR: 'el-progress-metric-card-sources-index-2-column',

        FOURTH_COLUMN: 'metric-card-sources-index-3-column',
        FOURTH_COLUMN_LABEL: 'metric-card-sources-index-3-column-label',
        FOURTH_COLUMN_TOOLTIP: 'metric-card-sources-index-3-column-tooltip',
        FOURTH_COLUMN_NUMBER: 'metric-card-sources-index-3-column-number',
        FOURTH_COLUMN_PROGRESS_BAR: 'el-progress-metric-card-sources-index-3-column',

        FIFTH_COLUMN: 'metric-card-sources-index-4-column',
        FIFTH_COLUMN_LABEL: 'metric-card-sources-index-4-column-label',
        FIFTH_COLUMN_TOOLTIP: 'metric-card-sources-index-4-column-tooltip',
        FIFTH_COLUMN_NUMBER: 'metric-card-sources-index-4-column-number',
        FIFTH_COLUMN_PROGRESS_BAR: 'el-progress-metric-card-sources-index-4-column'
    },

    VIEWS: {
        LABEL: 'widget-label-views',
        TOOLTIP: 'widget-tooltip-views',
        GO_TO_VIEWS_LINK: 'widget-link-go-to-views',
        GO_TO_VIEWS_LINK_ARROW: 'widget-arrow-go-to-views',

        TOTAL_VIEWS_COLUMN: 'metric-card-views-index-0-column',
        TOTAL_VIEWS_LABEL: 'metric-card-views-index-0-column-label',
        TOTAL_VIEWS_TOOLTIP: 'metric-card-views-index-0-column-tooltip',
        TOTAL_VIEWS_NUMBER: 'metric-card-views-index-0-column-number',

        UNIQUE_VIEWS_COLUMN: 'metric-card-views-index-1-colum',
        UNIQUE_VIEWS_LABEL: 'metric-card-views-index-1-column-label',
        UNIQUE_VIEWS_TOOLTIP: 'metric-card-views-index-1-column-tooltip',
        UNIQUE_VIEWS_NUMBER: 'metric-card-views-index-1-column-number',

        BOUNCE_RATE_COLUMN: 'metric-card-views-index-2-colum',
        BOUNCE_RATE_LABEL: 'metric-card-views-index-2-column-label',
        BOUNCE_RATE_TOOLTIP: 'metric-card-views-index-2-column-tooltip',
        BOUNCE_RATE_NUMBER: 'metric-card-views-index-2-column-number',
        BOUNCE_RATE_PROGRESS_BAR: 'el-progress-metric-card-views-index-2-column'
    },

    TECHNOLOGY: (index = 0) => {
        return {
            LABEL: 'widget-label-technology',
            TOOLTIP: 'widget-tooltip-technology',
            GO_TO_TECHNOLOGY_LINK: 'widget-link-go-to-technology',
            GO_TO_TECHNOLOGY_LINK_ARROW: 'widget-arrow-go-to-technology',

            TOP_PLATFORMS_LABEL: 'cly-section-label-top-platforms',
            TOP_PLATFORMS_TOOLTIP: 'cly-section-top-platforms-tooltip',
            TOP_PLATFORMS_DATA_BLOCK: 'cly-section-top-platforms-data-block',
            TOP_PLATFORMS_DATA_BLOCK_ITEMS: '[data-test-id="cly-section-top-platforms-data-block"] .version-graph-block.bu-p-3',
            TOP_PLATFORMS_ITEM: 'cly-section-top-platforms-item-' + index,
            TOP_PLATFORMS_NAME: 'cly-section-top-platforms-item-' + index + '-name',
            TOP_PLATFORMS_VALUE: 'cly-section-top-platforms-item-' + index + '-value',
            TOP_PLATFORMS_PERCENT: 'cly-section-top-platforms-item-' + index + '-percent',
            TOP_PLATFORMS_PROGRESS_BAR: 'cly-section-top-platforms-item-' + index + '-progress-bar',

            TOP_DEVICES_LABEL: 'cly-section-label-top-devices',
            TOP_DEVICES_TOOLTIP: 'cly-section-top-devices-tooltip',
            TOP_DEVICES_DATA_BLOCK: 'cly-section-top-devices-data-block',
            TOP_DEVICES_DATA_BLOCK_ITEMS: '[data-test-id="cly-section-top-devices-data-block"] .version-graph-block.bu-p-3',
            TOP_DEVICES_ITEM: 'cly-section-devices-item-' + index,
            TOP_DEVICES_NAME: 'cly-section-devices-item-' + index + '-name',
            TOP_DEVICES_VALUE: 'cly-section-devices-item-' + index + '-value',
            TOP_DEVICES_PERCENT: 'cly-section-devices-item-' + index + '-percent',
            TOP_DEVICES_PROGRESS_BAR: 'cly-section-devices-item-' + index + '-progress-bar',

            TOP_APP_VERSIONS_LABEL: 'cly-section-label-top-app-versions',
            TOP_APP_VERSIONS_TOOLTIP: 'cly-section-top-app-versions-tooltip',
            TOP_APP_VERSIONS_DATA_BLOCK: 'cly-section-top-app-versions-data-block',
            TOP_APP_VERSIONS_DATA_BLOCK_ITEMS: '[data-test-id="cly-section-top-app-versions-data-block"] .version-graph-block.bu-p-3',
            TOP_APP_VERSIONS_ITEM: 'cly-section-top-app-versions-item-' + index,
            TOP_APP_VERSIONS_NAME: 'cly-section-top-app-versions-item-' + index + '-name',
            TOP_APP_VERSIONS_VALUE: 'cly-section-top-app-versions-item-' + index + '-value',
            TOP_APP_VERSIONS_PERCENT: 'cly-section-top-app-versions-item-' + index + '-percent',
            TOP_APP_VERSIONS_PROGRESS_BAR: 'cly-section-top-app-versions-item-' + index + '-progress-bar',

            TOP_DEVICE_TYPES_LABEL: 'cly-section-label-top-device-types',
            TOP_DEVICE_TYPES_TOOLTIP: 'cly-section-top-device-types-tooltip',
            TOP_DEVICE_TYPES_DATA_BLOCK: 'cly-section-top-device-types-data-block',
            TOP_DEVICE_TYPES_DATA_BLOCK_ITEMS: '[data-test-id="cly-section-top-device-types-data-block"] .version-graph-block.bu-p-3',
            TOP_DEVICE_TYPES_ITEM: 'cly-section-top-device-types-item-' + index,
            TOP_DEVICE_TYPES_NAME: 'cly-section-top-device-types-item-' + index + '-name',
            TOP_DEVICE_TYPES_VALUE: 'cly-section-top-device-types-item-' + index + '-value',
            TOP_DEVICE_TYPES_PERCENT: 'cly-section-top-device-types-item-' + index + '-percent',
            TOP_DEVICE_TYPES_PROGRESS_BAR: 'cly-section-top-device-types-item-' + index + '-progress-bar',
        };
    },

    COUNTRIES: {
        LABEL: 'widget-label-countries',
        TOOLTIP: 'widget-tooltip-countries',
        GO_TO_COUNTRIES_LINK: 'widget-link-go-to-countries',
        GO_TO_COUNTRIES_LINK_ARROW: 'widget-arrow-go-to-countries',
        WORLD_MAP: 'cly-worldmap',
        BUTTON_SHOW_COUNTRY: 'button-show-turkey',

        TOTAL_SESSIONS_RADIO_BUTTON: 'cly-radio-button-box-total-sessions',
        TOTAL_SESSIONS_RADIO_BOX: 'cly-radio-box-total-sessions',
        TOTAL_SESSIONS_LABEL: 'cly-radio-label-total-sessions',
        TOTAL_SESSIONS_NUMBER: 'cly-radio-number-total-sessions',
        TOTAL_SESSIONS_TREND_ICON: 'cly-radio-trend-icon-total-sessions',
        TOTAL_SESSIONS_TREND_VALUE: 'cly-radio-trend-total-sessions',

        TOTAL_USERS_RADIO_BUTTON: 'cly-radio-button-box-total-users',
        TOTAL_USERS_RADIO_BOX: 'cly-radio-box-total-users',
        TOTAL_USERS_LABEL: 'cly-radio-label-total-users',
        TOTAL_USERS_NUMBER: 'cly-radio-number-total-users',
        TOTAL_USERS_TREND_ICON: 'cly-radio-trend-icon-total-users',
        TOTAL_USERS_TREND_VALUE: 'cly-radio-trend-total-users',

        NEW_USERS_RADIO_BUTTON: 'cly-radio-button-box-new-users',
        NEW_USERS_RADIO_BOX: 'cly-radio-box-new-users',
        NEW_USERS_LABEL: 'cly-radio-label-new-users',
        NEW_USERS_NUMBER: 'cly-radio-number-new-users',
        NEW_USERS_TREND_ICON: 'cly-radio-trend-icon-new-users',
        NEW_USERS_TREND_VALUE: 'cly-radio-trend-new-users',
    },

    CRASH_STATISTICS: {
        LABEL: 'widget-label-crash-statistics',
        TOOLTIP: 'widget-tooltip-crash-statistics',
        GO_TO_CRASHES_LINK: 'widget-link-go-to-crashes',
        GO_TO_CRASHES_LINK_ARROW: 'widget-arrow-go-to-crashes',

        TOTAL_CRASHES_LABEL: 'metric-card-crashes-index-0-column-label',
        TOTAL_CRASHES_TOOLTIP: 'metric-card-crashes-index-0-column-tooltip',
        TOTAL_CRASHES_NUMBER: 'metric-card-crashes-index-0-column-number',
        TOTAL_CRASHES_TREND_ICON: 'metric-card-crashes-index-0-coloumn-trend-icon',
        TOTAL_CRASHES_TREND_VALUE: 'metric-card-crashes-index-0-coloumn-trend-desc',

        UNIQUE_CRASHES_LABEL: 'metric-card-crashes-index-1-column-label',
        UNIQUE_CRASHES_TOOLTIP: 'metric-card-crashes-index-1-column-tooltip',
        UNIQUE_CRASHES_NUMBER: 'metric-card-crashes-index-1-column-number',
        UNIQUE_CRASHES_TREND_ICON: 'metric-card-crashes-index-1-coloumn-trend-icon',
        UNIQUE_CRASHES_TREND_VALUE: 'metric-card-crashes-index-1-coloumn-trend-desc',

        CRASHES_SESSIONS_LABEL: 'metric-card-crashes-index-2-column-label',
        CRASHES_SESSIONS_TOOLTIP: 'metric-card-crashes-index-2-column-tooltip',
        CRASHES_SESSIONS_NUMBER: 'metric-card-crashes-index-2-column-number',
        CRASHES_SESSIONS_TREND_ICON: 'metric-card-crashes-index-2-coloumn-trend-icon',
        CRASHES_SESSIONS_TREND_VALUE: 'metric-card-crashes-index-2-coloumn-trend-desc',

        CRASH_FREE_USERS_LABEL: 'metric-card-crashes-index-3-column-label',
        CRASH_FREE_USERS_TOOLTIP: 'metric-card-crashes-index-3-column-tooltip',
        CRASH_FREE_USERS_NUMBER: 'metric-card-crashes-index-3-column-number',
        CRASH_FREE_USERS_TREND_ICON: 'metric-card-crashes-index-3-coloumn-trend-icon',
        CRASH_FREE_USERS_TREND_VALUE: 'metric-card-crashes-index-3-coloumn-trend-desc',

        CRASH_FREE_SESSIONS_LABEL: 'metric-card-crashes-index-4-column-label',
        CRASH_FREE_SESSIONS_TOOLTIP: 'metric-card-crashes-index-4-column-tooltip',
        CRASH_FREE_SESSIONS_NUMBER: 'metric-card-crashes-index-4-column-number',
        CRASH_FREE_SESSIONS_TREND_ICON: 'metric-card-crashes-index-4-coloumn-trend-icon',
        CRASH_FREE_SESSIONS_TREND_VALUE: 'metric-card-crashes-index-4-coloumn-trend-desc'
    },
};