export default {
    PAGE_TITLE: 'header-title',
    PAGE_TITLE_TOOLTIP: 'header-title-tooltip',
    FILTER_DATE_PICKER: 'cly-datepicker-test-id-pseudo-input-label',
    TAB_DEVICES: 'tab-devices-title',
    TAB_TYPES: 'tab-type-title',
    EMPTY_PIE_DEVICES_TOTAL_ICON: 'pie-devices-total-empty-logo',
    EMPTY_PIE_DEVICES_TOTAL_TITLE: 'pie-devices-total-empty-title',
    EMPTY_PIE_DEVICES_TOTAL_SUBTITLE: 'pie-devices-total-empty-subtitle',
    EMPTY_PIE_DEVICES_NEW_ICON: 'pie-devices-new-empty-logo',
    EMPTY_PIE_DEVICES_NEW_TITLE: 'pie-devices-new-empty-title',
    EMPTY_PIE_DEVICES_NEW_SUBTITLE: 'pie-devices-new-empty-subtitle',
    EMPTY_PIE_TYPES_TOTAL_ICON: 'pie-types-total-empty-logo',
    EMPTY_PIE_TYPES_TOTAL_TITLE: 'pie-types-total-empty-title',
    EMPTY_PIE_TYPES_TOTAL_SUBTITLE: 'pie-types-total-empty-subtitle',
    EMPTY_PIE_TYPES_NEW_ICON: 'pie-types-new-empty-logo',
    EMPTY_PIE_TYPES_NEW_TITLE: 'pie-types-new-empty-title',
    EMPTY_PIE_TYPES_NEW_SUBTITLE: 'pie-types-new-empty-subtitle',
    EMPTY_TABLE_ICON: 'cly-datatable-n-test-id-empty-logo',
    EMPTY_TABLE_TITLE: 'cly-datatable-n-test-id-empty-title',
    EMPTY_TABLE_SUBTITLE: 'cly-datatable-n-test-id-empty-subtitle',
    TAB_PLATFORMS: 'tab-platforms-title',
    TAB_DEVICES_AND_TYPES: 'tab-devices-and-types-title',
    TAB_RESOLUTIONS: 'tab-resolutions-title',
    TAB_APP_VERSIONS: 'tab-technology-versions-title',
    TAB_CARRIERS: 'tab-technology-carriers-title',
    TAB_DENSITIES: 'tab-technology-densities-title',
};