export default {
    PAGE_TITLE: 'header-title',
    PAGE_TITLE_TOOLTIP: 'header-title-tooltip',
    FILTER_DATE_PICKER: 'cly-datepicker-test-id-pseudo-input-label',
    EMPTY_TABLE_ICON: 'cly-datatable-n-test-id-empty-logo',
    EMPTY_TABLE_TITLE: 'cly-datatable-n-test-id-empty-title',
    EMPTY_TABLE_SUBTITLE: 'cly-datatable-n-test-id-empty-subtitle',
    TAB_PLATFORMS: 'tab-platforms-title',
    TAB_DEVICES_AND_TYPES: 'tab-devices-and-types-title',
    TAB_RESOLUTIONS: 'tab-resolutions-title',
    TAB_APP_VERSIONS: 'tab-technology-versions-title',
    TAB_CARRIERS: 'tab-technology-carriers-title',
    TAB_DENSITIES: 'tab-technology-densities-title',
    PLATFORMS_FOR_LABEL: 'platforms-for-label',
    PLATFORMS_FOR_LABEL_COMBOBOX: 'platforms-for-combobox-select-input-pseudo-input-label',
    PLATFORMS_FOR_TOTAL_SESSIONS_OPTION: 't-total-sessions-el-options',
    PLATFORMS_FOR_TOTAL_USERS_OPTION: 'u-total-users-el-options',
    PLATFORMS_FOR_NEW_USERS_OPTION: 'n-new-users-el-options',
    PLATFORMS_FOR_NO_DATA_LABEL: 'platforms-for-no-data-label',
    PLATFORMS_VERSION_DISTRIBUTION_LABEL: 'platforms-version-distribution-label',
    PLATFORMS_VERSION_DISTRIBUTION_NO_DATA_LABEL: 'platforms-version-distribution-no-data-label',
};