export default {
    PAGE_TITLE: 'header-title',
    PAGE_TITLE_TOOLTIP: 'header-title-tooltip',
    FILTER_DATE_PICKER: 'cly-datepicker-test-id-pseudo-input-label',
    EMPTY_PIE_NEW_ICON: 'pie-new-empty-logo',
    EMPTY_PIE_NEW_TITLE: 'pie-new-empty-title',
    EMPTY_PIE_NEW_SUBTITLE: 'pie-new-empty-subtitle',
    EMPTY_PIE_TOTAL_ICON: 'pie-total-empty-logo',
    EMPTY_PIE_TOTAL_TITLE: 'pie-total-empty-title',
    EMPTY_PIE_TOTAL_SUBTITLE: 'pie-total-empty-subtitle',
    EMPTY_TABLE_ICON: 'cly-datatable-n-test-id-empty-logo',
    EMPTY_TABLE_TITLE: 'cly-datatable-n-test-id-empty-title',
    EMPTY_TABLE_SUBTITLE: 'cly-datatable-n-test-id-empty-subtitle',
    TAB_PLATFORMS: 'tab-platforms-title',
    TAB_DEVICES_AND_TYPES: 'tab-devices-and-types-title',
    TAB_RESOLUTIONS: 'tab-resolutions-title',
    TAB_APP_VERSIONS: 'tab-technology-versions-title',
    TAB_CARRIERS: 'tab-technology-carriers-title',
    TAB_DENSITIES: 'tab-technology-densities-title',
};