export default {
    PAGE_TITLE: 'header-title',
    PAGE_TITLE_TOOLTIP: 'header-title-tooltip',
    FILTER_DATE_PICKER: 'cly-datepicker-test-id-pseudo-input-label',
    APP_VERSIONS_FOR_LABEL: 'app-versions-for-label',
    APP_VERSIONS_FOR_COMBOBOX: 'app-versions-for-select-input-pseudo-input-label',
    AS_LABEL: 'as-label',
    AS_VALUE_COMBOBOX: 'as-value-select-input-pseudo-input-label',
    EMPTY_CHART_PAGE_ICON: 'cly-chart-bar-test-id-empty-logo',
    EMPTY_CHART_PAGE_TITLE: 'cly-chart-bar-test-id-empty-title',
    EMPTY_CHART_PAGE_SUBTITLE: 'cly-chart-bar-test-id-empty-subtitle',
    EMPTY_TABLE_ICON: 'cly-datatable-n-test-id-empty-logo',
    EMPTY_TABLE_TITLE: 'cly-datatable-n-test-id-empty-title',
    EMPTY_TABLE_SUBTITLE: 'cly-datatable-n-test-id-empty-subtitle',
    TAB_PLATFORMS: 'tab-platforms-title',
    TAB_DEVICES_AND_TYPES: 'tab-devices-and-types-title',
    TAB_RESOLUTIONS: 'tab-resolutions-title',
    TAB_APP_VERSIONS: 'tab-technology-versions-title',
    TAB_CARRIERS: 'tab-technology-carriers-title',
    TAB_DENSITIES: 'tab-technology-densities-title',
};