receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  memory_limiter:
    limit_mib: 512
  k8sattributes:
    extract:
      metadata:
        - k8s.pod.name
        - k8s.namespace.name
        - k8s.deployment.name
      labels:
        - tag_name: app
          key: app
          from: pod
  resource:
    attributes:
      - key: service.namespace
        value: countly
        action: upsert

exporters:
  prometheusremotewrite:
    endpoint: ${env:OTEL_EXPORTER_PROMETHEUS_ENDPOINT}${env:PROMETHEUS_REMOTE_WRITE_PATH}
    headers:
      Authorization: Bearer ${env:PROMETHEUS_BEARER_TOKEN}
    timeout: 30s
  
  otlp/tempo:
    endpoint: ${env:OTEL_EXPORTER_TEMPO_ENDPOINT}
    headers:
      Authorization: ${env:TEMPO_AUTH_HEADER}
    tls:
      insecure: ${env:OTEL_EXPORTER_TLS_INSECURE}
    timeout: 30s
  
  loki:
    endpoint: ${env:OTEL_EXPORTER_LOKI_ENDPOINT}${env:LOKI_PUSH_PATH}
    headers:
      X-Scope-OrgID: ${env:LOKI_TENANT_ID}
    timeout: 30s
  
  logging:

service:
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, memory_limiter, k8sattributes, resource]
      exporters: [otlp/tempo, logging]
    
    metrics:
      receivers: [otlp]
      processors: [batch, memory_limiter, k8sattributes, resource]
      exporters: [prometheusremotewrite, logging]
    
    logs:
      receivers: [otlp]
      processors: [batch, memory_limiter, k8sattributes, resource]
      exporters: [loki, logging]

extensions:
  health_check:
    endpoint: 0.0.0.0:13133
