apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: ingress-nginx
  annotations:
    kustomize.config.k8s.io/behavior: merge
data:
  # Enable OpenTelemetry tracing
  enable-opentelemetry: "true"
  
  # OpenTelemetry collector endpoint
  otlp-collector-host: "alloy.countly-observability.svc.cluster.local"
  otlp-collector-port: "4317"
  
  # OpenTelemetry service configuration
  otel-service-name: "nginx-ingress"
  otel-max-queuesize: "2048"
  otel-sampler: "AlwaysOn"  # No sampling - trace all requests
  otel-sampler-ratio: "1.0"  # 100% sampling
  
  # Trust incoming spans to maintain trace continuity
  opentelemetry-trust-incoming-span: "true"
  
  # Enhanced logging with request correlation and trace context
  log-format-upstream: >
    $remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent
    "$http_referer" "$http_user_agent" $request_time $upstream_response_time
    request_id=$req_id trace_context=$http_traceparent traceId=$opentelemetry_trace_id
    spanId=$opentelemetry_span_id
  
  # Generate unique request IDs for correlation
  generate-request-id: "true"
  
  # Forward trace context headers to upstream
  proxy-set-headers: "ingress-nginx/custom-headers"

  # Performance tuning settings
  worker-processes: "auto"
  worker-connections: "65535"
  worker-rlimit-nofile: "131072"
  keepalive-timeout: "120"
  keepalive-requests: "10000"
  proxy-connect-timeout: "10"
  proxy-send-timeout: "120"
  proxy-read-timeout: "120"

  proxy-buffering: "on"
  proxy-buffers: "16 256k"
  proxy-buffer-size: "256k"
  proxy-busy-buffers-size: "512k"
  proxy-max-temp-file-size: "2048m"

  upstream-keepalive-connections: "100"
  upstream-keepalive-requests: "1000"
  upstream-keepalive-timeout: "60"

  client-max-body-size: "50m"
  client-body-buffer-size: "1m"
  client-body-timeout: "120"
  client-header-timeout: "120"

  server-name-hash-bucket-size: "256"
  server-name-hash-max-size: "2048"
  variables-hash-bucket-size: "512"
  variables-hash-max-size: "4096"
  map-hash-bucket-size: "512"
  map-hash-max-size: "4096"