apiVersion: v1
kind: Secret
metadata:
  name: countly-tls
data:
  tls.crt: YOUR_SSL_CERT_IN_BASE64      # cat cert.crt | base64
  tls.key: YOUR_SSL_KEY_IN_BASE64       # cat cert.key | base64
type: kubernetes.io/tls
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: countly-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  tls:
  - hosts:
    - YOUR_HOSTNAME                     # countly.example.com
    secretName: countly-tls
  rules:
  - host: YOUR_HOSTNAME                 # countly.example.com
    http:
      paths:
      - path: /i
        pathType: ImplementationSpecific
        backend:
          service:
            name: countly-api
            port:
              number: 3001
      - path: /i/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: countly-api
            port:
              number: 3001
      - path: /o
        pathType: ImplementationSpecific
        backend:
          service:
            name: countly-api
            port:
              number: 3001
      - path: /o/*
        pathType: ImplementationSpecific
        backend:
          service:
            name: countly-api
            port:
              number: 3001
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: countly-frontend
            port:
              number: 6001
