objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: countly
    name: countly-mongodb
  spec:
    ports:
    - port: 27017
      targetPort: 27017
    selector:
      name: countly-mongodb
