export default {
    //Common elements
    LOGO: 'countly-logo',
    PAGE_TITLE: 'initial-setup-title',
    SELECT_APP_TYPE_LABEL: 'select-application-type-form-header',
    APP_TYPE_MOBILE_RADIO_BUTTON: 'initial-setup-mobile-el-radio-wrapper',
    APP_TYPE_MOBILE_RADIO_BUTTON_ICON: 'initial-setup-mobile-icon',
    APP_TYPE_MOBILE_RADIO_BUTTON_LABEL: 'initial-setup-mobile-el-radio-label',
    APP_TYPE_WEB_RADIO_BUTTON: 'initial-setup-web-el-radio-wrapper',
    APP_TYPE_WEB_RADIO_BUTTON_ICON: 'initial-setup-web-icon',
    APP_TYPE_WEB_RADIO_BUTTON_LABEL: 'initial-setup-web-el-radio-label',
    APP_TYPE_DESKTOP_RADIO_BUTTON: 'initial-setup-desktop-el-radio-wrapper',
    APP_TYPE_DESKTOP_RADIO_BUTTON_ICON: 'initial-setup-desktop-icon',
    APP_TYPE_DESKTOP_RADIO_BUTTON_LABEL: 'initial-setup-desktop-el-radio-label',
    SELECT_TIMEZONE_LABEL: 'select-timezone-form-header',
    SELECT_TIMEZONE_TOOLTIP: 'select-timezone-form-tooltip',
    SELECT_TIMEZONE_COMBOBOX: 'select-timezone-dropdown',
    SELECT_TIMEZONE_SEARCH_INPUT: 'select-timezone-dropdown-search-box',
    CONTINUE_SUBMIT_BUTTON: 'continue-submit-button',

    //"Own App" Elements
    APPLICATION_NAME_LABEL: 'application-name-header',
    PAGE_SUB_TITLE: 'initial-setup-sub-title',
    APPLICATION_NAME_INPUT: 'app-name-input',
    APPLICATION_NAME_ERROR: 'app-name-error',
    APPLICATION_KEY_LABEL: 'application-key-header',
    APPLICATION_KEY_TOOLTIP: 'application-key-tooltip',
    APPLICATION_KEY_INPUT: 'app-key-input',
    APPLICATION_KEY_ERROR: 'app-key-error',

    //"DemoApp" Elements
    SELECT_DEMO_DATA_TYPE_LABEL: 'select-demo-type-form-header',
    DATA_TYPE_BANKING_RADIO_BUTTON: 'app-template-banking-el-radio-wrapper',
    DATA_TYPE_BANKING_RADIO_BUTTON_ICON: 'app-template-banking-icon',
    DATA_TYPE_BANKING_RADIO_BUTTON_LABEL: 'app-template-banking-el-radio-label',
    DATA_TYPE_HEALTHCARE_RADIO_BUTTON: 'app-template-healthcare-el-radio-wrapper',
    DATA_TYPE_HEALTHCARE_RADIO_BUTTON_ICON: 'app-template-healthcare-icon',
    DATA_TYPE_HEALTHCARE_RADIO_BUTTON_LABEL: 'app-template-healthcare-el-radio-label',
    DATA_TYPE_NAVIGATION_RADIO_BUTTON: 'app-template-navigation-el-radio-wrapper',
    DATA_TYPE_NAVIGATION_RADIO_BUTTON_ICON: 'app-template-navigation-icon',
    DATA_TYPE_NAVIGATION_RADIO_BUTTON_LABEL: 'app-template-navigation-el-radio-label',
    DATA_TYPE_ECOMMERCE_RADIO_BUTTON: 'app-template-ecommerce-el-radio-wrapper',
    DATA_TYPE_ECOMMERCE_RADIO_BUTTON_ICON: 'app-template-ecommerce-icon',
    DATA_TYPE_ECOMMERCE_RADIO_BUTTON_LABEL: 'app-template-ecommerce-el-radio-label',
    DATA_TYPE_GAMING_RADIO_BUTTON: 'app-template-gaming-el-radio-wrapper',
    DATA_TYPE_GAMING_RADIO_BUTTON_ICON: 'app-template-gaming-icon',
    DATA_TYPE_GAMING_RADIO_BUTTON_LABEL: 'app-template-gaming-el-radio-label',
    //Data Populator Progress elements 
    DATA_POP_PROGRESS_BAR_IMG: 'populator-progress-bar-img',
    DATA_POP_PROGRESS_BAR: 'populator-progress',
    DATA_POP_PROGRESS_BAR_TEXT: 'populator-progress-text',
    CONTINUE_BUTTON: 'continue-button'
};