export const feedbackRatingWidgetsPageElements = {
    //Empty Page Elements 
    RATINGS_WIDGETS_EMPTY_PAGE_ICON: 'ratings-widgets-empty-view-icon',
    RATINGS_WIDGETS_EMPTY_PAGE_TITLE: 'ratings-widgets-empty-view-title',
    RATINGS_WIDGETS_EMPTY_PAGE_SUBTITLE: 'ratings-widgets-empty-view-subtitle',
    RATINGS_WIDGETS_EMPTY_PAGE_ADD_NEW_WIDGET_BUTTON: 'ratings-widgets-empty-view-action-button',
  
    //Widgets Page's Elements
    RATING_WIDGETS_HEADER_TITLE_LABEL: 'ratings-widgets-header-title',
    ADD_NEW_WIDGET_BUTTON: 'ratings-widgets-add-button',
  
    //Add New Widget (Drawer) Pages' Elements
    ADD_NEW_WIDGET_HEADER_TITLE_LABEL: 'ratings-drawer-header-title',
    STEP_SIGN_NUMBER_ONE: 'ratings-drawer-current-step-index-1',
    STEP_SETTINGS_LABEL: 'ratings-drawer-settings-label',
    STEP_SEPERATOR_ONE: 'ratings-drawer-seperator-0',
    STEP_SIGN_NUMBER_TWO: 'ratings-drawer-current-step-index-2',
    STEP_APPEARANCE_LABEL: 'ratings-drawer-widget-appearance-label',
    STEP_SEPERATOR_TWO: 'ratings-drawer-seperator-1',
    STEP_SIGN_NUMBER_THREE: 'ratings-drawer-current-step-index-3',
    STEP_DEVICES_LABEL: 'ratings-drawer-devices-targeting-label',
    STEP_SETTINGS_CHECK_ICON: '[data-test-id="ratings-drawer-step-1-label"].is-passed',
    STEP_APPEARANCE_CHECK_ICON: '[data-test-id="ratings-drawer-step-2-label"].is-passed',
    CLOSE_ICON: 'ratings-drawer-close-button',
    QUESTION_LABEL: 'ratings-drawer-settings-question-label',
    QUESTION_INPUT: 'ratings-drawer-settings-question-input',
    RATINGS_LABEL: 'ratings-drawer-settings-ratings-label',
    EMOJI_ONE_TEXT_INPUT: 'ratings-drawer-settings-ratings-emoji1-text-input',
    EMOJI_TWO_TEXT_INPUT: 'ratings-drawer-settings-ratings-emoji2-text-input',
    EMOJI_THREE_TEXT_INPUT: 'ratings-drawer-settings-ratings-emoji3-text-input',
    EMOJI_FOUR_TEXT_INPUT: 'ratings-drawer-settings-ratings-emoji4-text-input',
    EMOJI_FIVE_TEXT_INPUT: 'ratings-drawer-settings-ratings-emoji5-text-input',
    ADD_COMMENT_CHECKBOX: 'ratings-drawer-settings-comment-checkbox-el-checkbox-input',
    ADD_COMMENT_LABEL: 'ratings-drawer-settings-comment-label',
    ADD_COMMENT_INPUT: 'ratings-drawer-settings-comment-input',
    CONTACT_VIA_CHECKBOX: 'ratings-drawer-settings-contact-checkbox-el-checkbox-input',
    CONTACT_VIA_LABEL: 'ratings-drawer-settings-contact-label',
    CONTACT_VIA_INPUT: 'ratings-drawer-settings-contact-input',
    BUTTON_CALLOUT_LABEL: 'ratings-drawer-settings-button-callout-label',
    BUTTON_CALLOUT_INPUT: 'ratings-drawer-settings-button-callout-input',
    THANKS_MESSAGE_LABEL: 'ratings-drawer-settings-thanks-label',
    THANKS_MESSAGE_INPUT: 'ratings-drawer-settings-thanks-input',
    RATING_SYMBOL_LABEL: 'ratings-drawer-appearance-rating-symbol-label',
    RATING_SYMBOL_COMBOBOX: 'ratings-drawer-select-input',
    LOGO_LABEL: 'ratings-drawer-appearance-logo-label',
    LOGO_TOOLTIP: 'ratings-drawer-appearance-logo-tooltip',
    LOGO_DEFAULT_LABEL: 'ratings-drawer-default-el-radio-label',
    LOGO_DEFAULT_RADIO_BUTTON: 'ratings-drawer-default-el-radio',
    LOGO_CUSTOM_LABEL: 'ratings-drawer-custom-el-radio-label',
    LOGO_CUSTOM_RADIO_BUTTON: 'ratings-drawer-custom-el-radio',
    LOGO_DONT_USE_LABEL: 'ratings-drawer-none-el-radio-label',
    LOGO_DONT_USE_RADIO_BUTTON: 'ratings-drawer-none-el-radio',
    UPLOAD_FILE_DROPZONE: '#logo-dropzone',
    UPLOAD_FILE_BUTTON: 'ratings-drawer-upload-image-model-click-upload-button',
    UPLOAD_FILE_ICON: 'ratings-drawer-upload-image-model-folder-icon',
    MAIN_COLOR_LABEL: 'ratings-drawer-appearance-main-color-label',
    MAIN_COLOR_COMBOBOX: 'ratings-drawer-appearance-main-color-dropdown',
    MAIN_COLOR_ICON: 'ratings-drawer-appearance-main-color-dropdown-cly-color-picker-img-wrapper',
    FONT_COLOR_LABEL: 'ratings-drawer-appearance-font-color-label',
    FONT_COLOR_COMBOBOX: 'ratings-drawer-appearance-font-color-dropdown',
    FONT_COLOR_ICON: 'ratings-drawer-appearance-font-color-dropdown-cly-color-picker-img-wrapper',
    TRIGGER_BUTTON_SIZE_LABEL: 'ratings-drawer-appearance-trigger-button-size-label',
    BUTTON_SIZE_SMALL_LABEL: 'ratings-drawer-s-el-radio-label',
    BUTTON_SIZE_SMALL_RADIO_BUTTON: 'ratings-drawer-s-el-radio',
    BUTTON_SIZE_MEDIUM_LABEL: 'ratings-drawer-m-el-radio-label',
    BUTTON_SIZE_MEDIUM_RADIO_BUTTON: 'ratings-drawer-m-el-radio',
    BUTTON_SIZE_LARGE_LABEL: 'ratings-drawer-l-el-radio-label',
    BUTTON_SIZE_LARGE_RADIO_BUTTON: 'ratings-drawer-l-el-radio',
    POSITION_ON_THE_PAGE_LABEL: 'ratings-drawer-appearance-position-on-the-page-label',
    POSITION_CENTER_LEFT_LABEL: 'ratings-drawer-mleft-label',
    POSITION_CENTER_LEFT_LOGO: 'ratings-drawer-mleft-logo',
    POSITION_CENTER_LEFT_RADIO_BUTTON: 'ratings-drawer-position-on-the-page-mleft-el-radio-wrapper',
    POSITION_CENTER_RIGHT_LABEL: 'ratings-drawer-mright-label',
    POSITION_CENTER_RIGHT_LOGO: 'ratings-drawer-mright-logo',
    POSITION_CENTER_RIGHT_RADIO_BUTTON: 'ratings-drawer-position-on-the-page-mright-el-radio-wrapper',
    POSITION_BOTTOM_LEFT_LABEL: 'ratings-drawer-bleft-label',
    POSITION_BOTTOM_LEFT_LOGO: 'ratings-drawer-bleft-logo',
    POSITION_BOTTOM_LEFT_RADIO_BUTTON: 'ratings-drawer-position-on-the-page-bleft-el-radio-wrapper',
    POSITION_BOTTOM_RIGHT_LABEL: 'ratings-drawer-bright-label',
    POSITION_BOTTOM_RIGHT_LOGO: 'ratings-drawer-bright-logo',
    POSITION_BOTTOM_RIGHT_RADIO_BUTTON: 'ratings-drawer-position-on-the-page-bright-el-radio-wrapper',
    TRIGGER_TEXT_LABEL: 'ratings-drawer-appearance-trigger-text-label',
    TRIGGER_TEXT_INPUT: 'ratings-drawer-appearance-trigger-text-input',
    VISIBILITY_LABEL: 'ratings-drawer-appearance-visibility-label',
    VISIBILITY_TOOLTIP: 'ratings-drawer-appearance-visibility-tooltip',
    HIDE_STICKER_CHECKBOX: 'ratings-drawer-appearance-hide-sticker-checkbox-el-checkbox-input',
    HIDE_STICKER_LABEL: 'ratings-drawer-appearance-hide-sticker-checkbox-el-checkbox-label',
    SHOW_ONLY_CHECKBOX: 'ratings-drawer-selected-pages-el-checkbox-input',
    SHOW_ONLY_LABEL: 'ratings-drawer-selected-pages-label',
    SHOW_ONLY_SELECTOR_LABEL: 'ratings-drawer-type-pages-label',
    SHOW_ONLY_SELECTOR: 'ratings-drawer-type-pages-select-select-input',
    SHOW_ONLY_SELECTOR_INPUT: 'ratings-drawer-type-pages-select-el-select-input',
    SET_ACTIVE_CHECKBOX: 'ratings-drawer-feedback-active-el-checkbox-input',
    SET_ACTIVE_LABEL: 'ratings-drawer-feedback-active-el-checkbox-label',
    CANCEL_BUTTON: 'ratings-drawer-cancel-button',
    NEXT_STEP_BUTTON: 'ratings-drawer-next-step-button',
    PREVIOUS_STEP_BUTTON: 'ratings-drawer-previous-step-button',
    SAVE_BUTTON: 'ratings-drawer-save-button',
  
    //Preview Page - Ratings Popup's Elements
    RATINGS_POPUP_LABEL: 'ratings-drawer-ratingspopup-label',
    RATINGS_POPUP_QUESTION_LABEL: 'ratings-drawer-ratingspopup-question',
    RATINGS_POPUP_EMOJI_ONE_ICON: 'ratings-drawer-ratingspopup-emoji1',
    RATINGS_POPUP_EMOJI_TWO_ICON: 'ratings-drawer-ratingspopup-emoji2',
    RATINGS_POPUP_EMOJI_THREE_ICON: 'ratings-drawer-ratingspopup-emoji3',
    RATINGS_POPUP_EMOJI_FOUR_ICON: 'ratings-drawer-ratingspopup-emoji4',
    RATINGS_POPUP_EMOJI_FIVE_ICON: 'ratings-drawer-ratingspopup-emoji5',
    RATINGS_POPUP_ADD_COMMENT_CHECKBOX: 'ratings-drawer-ratingspopup-comment-checkbox-el-checkbox-input',
    RATINGS_POPUP_ADD_COMMENT_LABEL: 'ratings-drawer-ratingspopup-comment-label',
    RATINGS_POPUP_CONTACT_VIA_CHECKBOX: 'ratings-drawer-ratingspopup-contact-checkbox-el-checkbox-input',
    RATINGS_POPUP_CONTACT_VIA_LABEL: 'ratings-drawer-ratingspopup-contact-label',
    RATINGS_POPUP_SUBMIT_BUTTON: 'ratings-drawer-ratingspopup-submit-button',
    RATINGS_POPUP_POWEREDBY_LOGO: 'ratings-drawer-ratingspopup-poweredby-label',
  
    //Preview Page - Thank you Message
    RATINGS_POPUP_THANK_YOU_MESSAGE_POPUP_LABEL: 'ratings-drawer-thankyoupopup-label',
    RATINGS_POPUP_SUCCESS_ICON: 'ratings-drawer-thankyoupopup-icon',
    RATINGS_POPUP_SUCCESS_ICON_COLOR: 'ratings-drawer-thankyoupopup-color-icon',
    RATINGS_POPUP_THANK_YOU_MESSAGE_TEXT: 'ratings-drawer-thankyoupopup-message-text',
    RATINGS_POPUP_THANK_YOU_MESSAGE_POWEREDBY_LOGO: 'ratings-drawer-thankyoupopup-poweredby-label',
  
    //Preview Page - Trigger Button Preview
    RATINGS_POPUP_TRIGGER_POPUP_LABEL: 'ratings-drawer-trigger-button-preview-label',
    RATINGS_POPUP_TRIGGER_BUTTON_LABEL: 'ratings-drawer-trigger-button-label',
    RATINGS_POPUP_TRIGGER_BUTTON: 'ratings-drawer-trigger-button'
  }
  
  const widgetsDataTableElements = (index = 0) => {
    return {
      TABLE_ROWS: '.el-table__row',
      EDIT_COLUMNS_BUTTON: 'ratings-widgets-data-table-edit-columns-button',
      EXPORT_AS_BUTTON: 'ratings-widgets-data-table-export-as-button',
      TABLE_SEARCH_INPUT: 'ratings-widgets-data-table-datatable-search-input',
      COLUMN_NAME_STATUS_LABEL: 'ratings-widgets-data-table-label-status',
      COLUMN_NAME_STATUS_SORTABLE_ICON: 'ratings-widgets-data-table-sortable-icon-status',
      COLUMN_NAME_RATINGS_WIDGET_NAME_LABEL: 'ratings-widgets-data-table-label-ratings-widget-name',
      COLUMN_NAME_TARGETING_LABEL: 'ratings-widgets-data-table-label-targeting',
      COLUMN_NAME_RATING_SCORE_LABEL: 'ratings-widgets-data-table-label-rating-score',
      COLUMN_NAME_RATING_SCORE_SORTABLE_ICON: 'ratings-widgets-data-table-sortable-icon-rating-score',
      COLUMN_NAME_RESPONSES_LABEL: 'ratings-widgets-data-table-label-responses',
      COLUMN_NAME_RESPONSES_SORTABLE_ICON: 'ratings-widgets-data-table-sortable-icon-responses',
      COLUMN_NAME_PAGES_LABEL: 'ratings-widgets-data-table-label-pages',
      COLUMN_NAME_PAGES_SORTABLE_ICON: 'ratings-widgets-data-table-sortable-icon-pages',
      //Columns' Rows' Datas Elements
      STATUS_SWITCH_WRAPPER: 'ratings-widgets-data-table-status-' + index + '-el-switch-wrapper',
      STATUS_SWITCH_INPUT: 'ratings-widgets-data-table-status-' + index + '-el-switch-input',
      WIDGET_QUESTION: 'ratings-widgets-data-table-widget-name-' + index,
      WIDGET_ID_LABEL: 'ratings-widgets-data-table-widget-id-label-' + index,
      WIDGET_ID: 'ratings-widgets-data-table-widget-id-value-' + index,
      TARGETING_ALL_USERS: 'ratings-widgets-data-table-targeting-' + index + '-all-users',
      TARGETING_PROPERTY_LABEL: 'ratings-widgets-data-table-targeting-' + index + '-seg-type-label',
      TARGETING_PROPERTY_SEGMENT: 'ratings-widgets-data-table-targeting-' + index + '-seg-type-value',
      TARGETING_BEHAVIOR_LABEL: 'ratings-widgets-data-table-targeting-' + index + '-cohorts-behavior-label',
      TARGETING_BEHAVIOR_SEGMENT: 'ratings-widgets-data-table-targeting-' + index + '-cohorts-behavior-value',
      RATING_SCORE: 'ratings-widgets-data-table-rating-score-' + index,
      RESPONSES: 'ratings-widgets-data-table-responses-' + index,
      PAGES: 'ratings-widgets-data-table-pages-' + index,
      //PAGINATION ELEMENTS
      ITEMS_PER_PAGE_LABEL: 'ratings-widgets-data-table-items-per-page-label',
      PER_PAGE_COUNT_SELECT: 'ratings-widgets-data-table-items-per-page-count-select-input-pseudo-input-label',
      PER_PAGE_COUNT_SELECT_ICON: 'ratings-widgets-data-table-items-per-page-count-select-icon',
      PER_PAGE_COUNT_LABEL: 'ratings-widgets-data-table-items-per-page-count-select',
      PAGE_NUMBER_SELECT: 'ratings-widgets-data-table-page-number-select-input-pseudo-input-label',
      PAGE_NUMBER_SELECT_ICON: 'ratings-widgets-data-table-page-number-select-icon',
      FIRST_PAGE_ARROW_BUTTON: 'ratings-widgets-data-table-first-page-arrow-button',
      PREVIOUS_PAGE_ARROW_BUTTON: 'ratings-widgets-data-table-previous-page-arrow-button',
      NEXT_PAGE_ARROW_BUTTON: 'ratings-widgets-data-table-next-page-arrow-button',
      LAST_PAGE_ARROW_BUTTON: 'ratings-widgets-data-table-last-page-arrow-button'
    };
  }
  
  export const feedbackRatingWidgetDetailsPageElements = {
    RATINGS_WIDGET_DETAILS_BACK_TO_RATING_WIDGETS_LINK_ICON: 'ratings-detail-back-link-icon',
    RATINGS_WIDGET_DETAILS_BACK_TO_RATING_WIDGETS_LINK:'ratings-detail-back-link-label',
    RATINGS_WIDGET_DETAILS_STOP_WIDGET_BUTTON: 'ratings-detail-stop-widget-button',
    RATINGS_WIDGET_DETAILS_START_WIDGET_BUTTON: 'ratings-detail-start-widget-button',
    RATINGS_WIDGET_DETAILS_EDIT_WIDGET_BUTTON: 'ratings-detail-edit-widget-button',
    RATINGS_WIDGET_DETAILS_MORE_BUTTON: 'ratings-detail-more-option-button',
    RATINGS_WIDGET_DETAILS_DELETE_BUTTON: 'ratings-detail',
    RATINGS_WIDGET_DETAILS_DELETE_CONFIRM_BUTTON: 'ratings-detail-cly-confirm-dialog-danger-button',
    RATINGS_WIDGET_DETAILS_QUESTION: 'ratings-detail-widget-name-label',
    RATINGS_WIDGET_DETAILS_STATUS_LABEL: 'ratings-detail-widget-status',
    RATINGS_WIDGET_DETAILS_CREATED_AT_ICON: 'ratings-detail-created-at-icon',
    RATINGS_WIDGET_DETAILS_CREATED_AT_LABEL: 'ratings-detail-created-at-label',
    RATINGS_WIDGET_DETAILS_CREATED_AT_VALUE: 'ratings-detail-created-at-value',
    RATINGS_WIDGET_DETAILS_PRICE_TAG_ICON: 'ratings-detail-price-tag-icon',
    RATINGS_WIDGET_DETAILS_WIDGET_ID_LABEL: 'ratings-detail-widget-id-label',
    RATINGS_WIDGET_DETAILS_WIDGET_ID_VALUE : 'ratings-detail-widget-id-value',
    RATINGS_WIDGET_DETAILS_TARGETING_LABEL_ARROW: 'ratings-detail-collapse-item-el-collapse-item-icon-left',
    RATINGS_WIDGET_DETAILS_TARGETING_LABEL: 'ratings-detail-collapse-item-el-collapse-item-label',
    RATINGS_WIDGET_DETAILS_ALL_USERS_LABEL: 'ratings-detail-all-users',
    RATINGS_WIDGET_DETAILS_PROPERTY_LABEL: 'ratings-detail-cohorts-property-label',
    RATINGS_WIDGET_DETAILS_PROPERTY_VALUE: 'ratings-detail-cohorts-property-value',
    RATINGS_WIDGET_DETAILS_BEHAVIOR_LABEL: 'ratings-detail-cohorts-behavior-label',
    RATINGS_WIDGET_DETAILS_BEHAVIOR_VALUE: 'ratings-detail-cohorts-behavior-value',
    RATINGS_WIDGET_DETAILS_RESULT_FOR_LABEL: 'ratings-detail-results-for-label',
    RATINGS_WIDGET_DETAILS_FILTER_PARAMETERS_COMBOBOX: 'ratings-detail-pseudo-input-label',
    RATINGS_WIDGET_DETAILS_FILTER_PARAMETERS_SELECT_PLATFORM_COMBOBOX: 'ratings-detail-platform-input',
    RATINGS_WIDGET_DETAILS_FILTER_PARAMETERS_SELECT_APP_VERSION_COMBOBOX: 'ratings-detail-app-version-input',
    RATINGS_WIDGET_DETAILS_FILTER_PARAMETERS_CONFIRM_BUTTON: 'ratings-detail-confirm-button',
    RATINGS_WIDGET_DETAILS_FILTER_PARAMETERS_CANCEL_BUTTON: 'ratings-detail-cancel-button',
    RATINGS_WIDGET_DETAILS_RATINGS_LABEL: 'ratings-detail-metric-card-widget-detail-ratings-label',
    RATINGS_WIDGET_DETAILS_RATINGS_TOOLTIP: 'ratings-detail-metric-card-widget-detail-ratings--tooltip',
    RATINGS_WIDGET_DETAILS_RATINGS_VALUE: 'ratings-detail-metric-card-widget-detail-ratings--number',
    RATINGS_WIDGET_DETAILS_RATINGS_RATE_LABEL: 'ratings-detail-metric-card-widget-detail-rate-label',
    RATINGS_WIDGET_DETAILS_RATINGS_RATE_TOOLTIP: 'ratings-detail-metric-card-widget-detail-rate--tooltip',
    RATINGS_WIDGET_DETAILS_RATINGS_RATE_PROGRESS: '.el-progress.el-progress--circle.el-progress--without-text',
    RATINGS_WIDGET_DETAILS_RATINGS_RATE_VALUE: 'ratings-detail-metric-card-widget-detail-rate--number',
    RATINGS_WIDGET_DETAILS_TIMES_SHOWN_LABEL: 'ratings-detail-metric-card-widget-detail-times-shown-label',
    RATINGS_WIDGET_DETAILS_TIMES_SHOWN_TOOLTIP: 'ratings-detail-metric-card-widget-detail-times-shown--tooltip',
    RATINGS_WIDGET_DETAILS_TIMES_SHOWN_VALUE: 'ratings-detail-metric-card-widget-detail-times-shown--number',
    RATINGS_WIDGET_DETAILS_TAB_RATINGS: 'ratings-detail-table-tab-ratings-title',
    RATINGS_WIDGET_DETAILS_TAB_COMMENTS: 'ratings-detail-table-tab-comments-title',
  }
  
  const feedbackRatingWidgetDetailsCommentsDataTableElements = (index = 0) => {
    return {
        TABLE_ROWS: '.el-table__row',
        EXPORT_AS_BUTTON: 'ratings-comments-table-export-as-button',
        TABLE_SEARCH_INPUT: 'ratings-comments-table-datatable-search-input',
        COLUMN_NAME_RATING_LABEL: 'ratings-comments-table-label-rating',
        COLUMN_NAME_RATING_SORTABLE_ICON: 'ratings-comments-table-sortable-icon-rating',
        COLUMN_NAME_TIME_LABEL: 'ratings-comments-table-label-time',
        COLUMN_NAME_TIME_SORTABLE_ICON: 'ratings-comments-table-sortable-icon-time',
        COLUMN_NAME_COMMENT_LABEL: 'ratings-comments-table-label-comment',
        COLUMN_NAME_EMAIL_LABEL: 'ratings-comments-table-label-e-mail',
        //Columns' Rows' Datas Elements
        ROW_RATING: 'ratings-comment-table-rating-row-' + index,
        ROW_TIME: 'ratings-comment-table-time-row-' + index,
        ROW_COMMENT: 'ratings-comment-table-comment-row-' + index,
        ROW_EMAIL: 'ratings-comment-table-time-email-row' + index,
  
        //PAGINATION ELEMENTS
        ITEMS_PER_PAGE_LABEL: 'ratings-comments-table-items-per-page-label',
        PER_PAGE_COUNT_SELECT: 'ratings-comments-table-items-per-page-count-select-input-pseudo-input-label',
        PER_PAGE_COUNT_SELECT_ICON: 'ratings-comments-table-items-per-page-count-select-icon',
        PER_PAGE_COUNT_LABEL: 'ratings-comments-table-items-per-page-count-select',
        PAGE_NUMBER_SELECT: 'ratings-comments-table-page-number-select-input-pseudo-input-label',
        PAGE_NUMBER_SELECT_ICON: 'ratings-comments-table-page-number-select-icon',
        FIRST_PAGE_ARROW_BUTTON: 'ratings-comments-table-first-page-arrow-button',
        PREVIOUS_PAGE_ARROW_BUTTON: 'ratings-comments-table-previous-page-arrow-button',
        NEXT_PAGE_ARROW_BUTTON: 'ratings-comments-table-next-page-arrow-button',
        LAST_PAGE_ARROW_BUTTON: 'ratings-comments-table-last-page-arrow-button'
    };
  };
  
    const feedbackRatingWidgetDetailsRatingsDataTableElements = (index = 0) => {
      return {
          TABLE_ROWS: '.el-table__row',
          EXPORT_AS_BUTTON: 'ratings-data-table-export-as-button',
          TABLE_SEARCH_INPUT: 'ratings-data-table-datatable-search-input',
          COLUMN_NAME_RATING_LABEL: 'ratings-data-table-label-rating',
          COLUMN_NAME_RATING_SORTABLE_ICON: 'ratings-data-table-sortable-icon-rating',
          COLUMN_NAME_NUMBER_OF_RATINGS_LABEL: 'ratings-data-table-label-number-of-ratings',
          COLUMN_NAME_NUMBER_OF_RATINGS_SORTABLE_ICON: 'ratings-data-table-sortable-icon-number-of-ratings',
          COLUMN_NAME_PERCENTAGE_LABEL: 'ratings-data-table-label-percentage',
          COLUMN_NAME_PERCENTAGE_SORTABLE_ICON: 'ratings-data-table-sortable-icon-percentage',
          //Columns' Rows' Datas Elements
          ROW_RATING: 'ratings-data-table-rating-' + index,
          ROW_NUMBER_OF_RATINGS: 'ratings-data-table-number-of-rating-' + index,
          ROW_PERCENTAGE: 'ratings-data-table-percentage-' + index,
  
          //PAGINATION ELEMENTS
          ITEMS_PER_PAGE_LABEL: 'ratings-data-table-items-per-page-label',
          PER_PAGE_COUNT_SELECT: 'ratings-data-table-items-per-page-count-select-input-pseudo-input-label',
          PER_PAGE_COUNT_SELECT_ICON: 'ratings-data-table-items-per-page-count-select-icon',
          PER_PAGE_COUNT_LABEL: 'ratings-data-table-items-per-page-count-select',
          PAGE_NUMBER_SELECT: 'ratings-data-table-page-number-select-input-pseudo-input-label',
          PAGE_NUMBER_SELECT_ICON: 'ratings-data-table-page-number-select-icon',
          FIRST_PAGE_ARROW_BUTTON: 'ratings-data-table-first-page-arrow-button',
          PREVIOUS_PAGE_ARROW_BUTTON: 'ratings-data-table-previous-page-arrow-button',
          NEXT_PAGE_ARROW_BUTTON: 'ratings-data-table-next-page-arrow-button',
          LAST_PAGE_ARROW_BUTTON: 'ratings-data-table-last-page-arrow-button'
      };
  };
  
  module.exports = {
    feedbackRatingWidgetsPageElements,
    feedbackRatingWidgetDetailsPageElements,
    widgetsDataTableElements,
    feedbackRatingWidgetDetailsCommentsDataTableElements,
    feedbackRatingWidgetDetailsRatingsDataTableElements
  };