apiVersion: apps/v1
kind: Deployment
metadata:
  name: strimzi-cluster-operator
  namespace: kafka
spec:
  template:
    spec:
      containers:
      - name: strimzi-cluster-operator
        env:
        - name: STRIMZI_LEADER_ELECTION_LEASE_NAMESPACE
          value: kafka