apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: countly-observability

resources:
# Observability namespace
- namespace.yaml
# Grafana Alloy deployment (replaces OTEL Collector and Promtail)
- alloy.yaml

generatorOptions:
  labels:
    app: countly-observability
    managed-by: kustomize

configMapGenerator:
- name: observability-config
  envs:
  - configs/observability.env

secretGenerator:
- name: observability-auth
  envs:
  - secrets/observability-auth.env

