apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-ingestor
  labels:
    app: countly-ingestor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countly-ingestor
  template:
    metadata:
      labels:
        app: countly-ingestor
    spec:
      containers:
      - name: countly-ingestor
        image: countly/countly-server:latest
        ports:
        - containerPort: 3001
        env:
        - name: COUNTLY_CONTAINER
          value: "ingestor"
        - name: COUNTLY_CONFIG_API_MONGODB_HOST
          value: "mongo"
        - name: COUNTLY_CONFIG_API_MONGODB_DB
          value: "countly"
        - name: COUNTLY_CONFIG_FRONTEND_MONGODB_HOST
          value: "mongo"
        - name: COUNTLY_CONFIG_FRONTEND_MONGODB_DB
          value: "countly"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /ping
            port: 3001
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ping
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: countly-ingestor
  labels:
    app: countly-ingestor
spec:
  selector:
    app: countly-ingestor
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP