apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: countly-observability
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:

    # 1 Tempo – created first
    - name: Tempo
      uid: tempo
      type: tempo
      access: proxy
      url: http://tempo.countly-observability.svc.cluster.local:3200
      jsonData:
        httpMethod: GET

    # 2 Loki – created second, regex is RE2‑safe
    - name: Loki
      uid: loki
      type: loki
      access: proxy
      url: http://loki.countly-observability.svc.cluster.local:3100
      isDefault: true
      jsonData:
        derivedFields:
          - name: traceID                           # ← exact key
            matcherRegex: 'traceId=([A-Fa-f0-9]{32})'
            url: ${__value.raw}                    # ← two dollar signs
            datasourceUid: tempo

    # 3 Prometheus – created last
    - name: Prometheus
      uid: prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.countly-observability.svc.cluster.local:9090
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: countly-observability
  labels:
    app: grafana
spec:
  type: ClusterIP
  selector:
    app: grafana
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: countly-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: countly-observability
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:12.1.0
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_PLUGINS_PREINSTALL
          value: grafana-pyroscope-app,grafana-exploretraces-app,grafana-lokiexplore-app,grafana-metricsdrilldown-app
        - name: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS
          value: grafana-pyroscope-app,grafana-exploretraces-app,grafana-metricsdrilldown-app
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /var/lib/grafana
        - name: datasources
          mountPath: /etc/grafana/provisioning/datasources
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
      securityContext:
        fsGroup: 472
        runAsNonRoot: true
        runAsUser: 472
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: datasources
        configMap:
          name: grafana-datasources