export default {
    PAGE_TITLE: 'header-title',
    PAGE_TITLE_GUIDE_BUTTON: 'view-guide-button',
    CREATE_NEW_MESSAGE_BUTTON: 'create-new-messsage-button',
    TOTAL_APP_USERS_LABEL: 'metric-card-total-app-users-column-label',
    TOTAL_APP_USERS_NUMBER_LABEL: 'metric-card-total-app-users-column-number',
    NOTIFICATION_ENABLED_USERS_LABEL: 'metric-card-notification-enabled-users-column-label',
    NOTIFICATION_ENABLED_USERS_NUMBER_LABEL: 'metric-card-notification-enabled-users-column-number',
    ENABLED_USERS_PERCENTAGE_LABEL: 'metric-card-enabled-users-percentage-column-label',
    ENABLED_USERS_PERCENTAGE_NUMBER_LABEL: 'metric-card-enabled-users-percentage-column-number',
    ENABLED_USERS_PERCENTAGE_PROGRESS_CIRCLE: 'el-progress-metric-card-enabled-users-percentage-column',
    ENABLED_USERS_PERCENTAGE_PROGRESS_TOOLTIP: 'metric-card-enabled-users-percentage-column-tooltip',
    RESULTS_FOR_LABEL: 'push-notifications-result-for-label',
    RESULTS_FOR_COMBOBOX: 'push-notifications-result-for-combobox',
    FILTER_PARAMETERS_SELECT: 'cly-multi-select-test-id-pseudo-input-label',
    EDIT_COLUMNS_BUTTON: 'cly-datatable-n-test-id-edit-columns-button',
    EXPORT_AS_BUTTON: 'cly-datatable-n-test-id-export-as-button',
    DATATABLE_SEARCH_INPUT: 'cly-datatable-n-test-id-datatable-search-input',
    EMPTY_TABLE_ICON: 'cly-datatable-n-test-id-empty-logo',
    EMPTY_TABLE_TITLE: 'cly-datatable-n-test-id-empty-title',
    EMPTY_TABLE_SUBTITLE: 'cly-datatable-n-test-id-empty-subtitle'
};