apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: brokers
  namespace: kafka
  labels: { strimzi.io/cluster: demo-kafka }
spec:
  replicas: 3
  roles: ["broker"]
  resources:
    requests: { cpu: "1", memory: "4Gi" }
    limits:   { cpu: "1", memory: "4Gi" }       # Guaranteed QoS
  jvmOptions:
    "-Xms": "2g"
    "-Xmx": "2g"                                 # leave RAM to page cache
    "-XX":
      "UseG1GC": "true"
      "MaxGCPauseMillis": "20"
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 100Gi
        class: pd-ssd
        deleteClaim: false
  template:
    pod:
      tolerations:
        - key: dedicated
          operator: Equal
          value: kafka
          effect: NoSchedule
      # Topology spread constraints ensure brokers are distributed across different nodes
      # maxSkew=1 means at most 1 broker difference between nodes for fault tolerance
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              strimzi.io/pool-name: brokers
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values: ["kafka"]