apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: countly

# Use the base configuration
resources:
- ../../base

# Additional ConfigMaps for observability
configMapGenerator:
- name: observability-config-otlp
  envs:
  - countly-otlp.env

# Apply observability patches to enable OTEL using inline strategic merge patches
# This ensures configmap references are resolved correctly within the same kustomization
patches:
- target:
    kind: Deployment
    name: countly-api
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-api
    spec:
      template:
        spec:
          containers:
          - name: countly-api
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-api-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-api"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-frontend
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-frontend
    spec:
      template:
        spec:
          containers:
          - name: countly-frontend
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-frontend-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-frontend"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-aggregator
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-aggregator
    spec:
      template:
        spec:
          containers:
          - name: countly-aggregator
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-aggregator-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-aggregator"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-ingestor
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-ingestor
    spec:
      template:
        spec:
          containers:
          - name: countly-ingestor
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-ingestor-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-ingestor"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-jobserver
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-jobserver
    spec:
      template:
        spec:
          containers:
          - name: countly-jobserver
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-jobserver-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-jobserver"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-clickhouse-writer
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-clickhouse-writer
    spec:
      template:
        spec:
          containers:
          - name: countly-clickhouse-writer
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-clickhouse-writer-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-clickhouse-writer"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

- target:
    kind: Deployment
    name: countly-clickhouse-updater
  patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: countly-clickhouse-updater
    spec:
      template:
        spec:
          containers:
          - name: countly-clickhouse-updater
            envFrom:
            - configMapRef:
                name: countly-config
            - configMapRef:
                name: countly-clickhouse-updater-config
            - secretRef:
                name: common-config
            - secretRef:
                name: mongodb-config
            - secretRef:
                name: clickhouse-config
            - configMapRef:
                name: observability-config-otlp
            env:
            - name: OTEL_SERVICE_NAME
              value: "countly-clickhouse-updater"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=countly,deployment.environment=production"

# Optional: Add observability stack if you want to deploy collectors
# - ../../observability-stack