apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the base configuration
resources:
- ../../base

# Additional ConfigMaps for observability
configMapGenerator:
- name: observability-config-otlp
  envs:
  - countly-otlp.env

# Apply observability patches to enable OTEL
# Each service gets its own patch file for better maintainability
patches:
- path: patches/countly-api-otel.yaml
- path: patches/countly-frontend-otel.yaml  
- path: patches/countly-aggregator-otel.yaml
- path: patches/countly-ingestor-otel.yaml
- path: patches/countly-jobserver-otel.yaml
- path: patches/countly-clickhouse-writer-otel.yaml
- path: patches/countly-clickhouse-updater-otel.yaml

# Optional: Add observability stack if you want to deploy collectors
# - ../../observability-stack