apiVersion: v1
kind: DeploymentConfig
metadata:
  name: {{ include "countly.fullname" . }}-frontend
  labels:
{{ include "countly.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        name: {{ include "countly.fullname" . }}-frontend
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: {{ include "countly.fullname" . }}-frontend
        image: "{{ .Values.image.frontend.image }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        envFrom:
        - configMapRef:
            name: {{ include "countly.fullname" . }}
        env:
        - name: COUNTLY_CONFIG_FRONTEND_MONGODB_HOST
          value: $(COUNTLY_MONGODB_SERVICE_HOST)
        - name: COUNTLY_CONFIG_FRONTEND_MONGODB_PORT
          value: $(COUNTLY_MONGODB_SERVICE_PORT)
        - name: COUNTLY_CONFIG_API_MONGODB_HOST
          value: $(COUNTLY_MONGODB_SERVICE_HOST)
        - name: COUNTLY_CONFIG_API_MONGODB_PORT
          value: $(COUNTLY_MONGODB_SERVICE_PORT)
        - name: COUNTLY_CONFIG_FRONTEND_MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: countly-mongodb
              key: mongodb-root-password
        ports:
        - containerPort: 6001
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
  triggers:
  - type: ConfigChange
