apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "countly.fullname" . }}
  labels:
{{ include "countly.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  - host: {{ .host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ include "countly.fullname" . }}-frontend
          servicePort: 6001
      - path: /o
        backend:
          serviceName: {{ include "countly.fullname" . }}-api
          servicePort: 3001
      - path: /i
        backend:
          serviceName: {{ include "countly.fullname" . }}-api
          servicePort: 3001
