apiVersion: v1
kind: Service
metadata:
  name: {{ include "countly.fullname" . }}-api
  labels:
{{ include "countly.labels" . | indent 4 }}
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    name: {{ include "countly.fullname" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
