/**
 * Mocha config for enterprise plugin tests
 * Runs ONLY enterprise-exclusive plugins (not in plugins.default.json)
 * This matches CI behavior in .github/workflows/ci-clickhouse.yml
 */

const fs = require('fs');
const path = require('path');

// Setup NODE_PATH for symlinked plugins to find core modules
const corePath = path.resolve(__dirname, '../../..');
const nodeModulesPath = path.resolve(corePath, 'node_modules');
process.env.NODE_PATH = [nodeModulesPath, corePath, process.env.NODE_PATH].filter(Boolean).join(':');
require('module').Module._initPaths();

const pluginsDir = path.resolve(__dirname, '../../../plugins');
const testPluginsDir = path.resolve(__dirname, '../../4.plugins');

// Source files (plugins repo is 4 levels up from core/test/configs/mocha)
const eePluginsPath = path.resolve(__dirname, '../../../../plugins/plugins.ee.json');
const defaultPluginsPath = path.resolve(pluginsDir, 'plugins.default.json');

// Destination files
const pluginsPath = path.resolve(pluginsDir, 'plugins.json');
const pluginsBackupPath = path.resolve(pluginsDir, 'plugins.json.test-backup');
const pluginsLitePath = path.resolve(pluginsDir, 'plugins.lite.json');
const testLoaderPath = path.resolve(testPluginsDir, '1.plugin.tests.js');
const testLoaderBackupPath = path.resolve(testPluginsDir, '1.plugin.tests.js.backup');

// Setup for EE-only tests (matching CI behavior)
if (fs.existsSync(eePluginsPath) && fs.existsSync(defaultPluginsPath)) {
    // Backup current files
    if (fs.existsSync(pluginsPath)) {
        fs.copyFileSync(pluginsPath, pluginsBackupPath);
    }
    if (fs.existsSync(testLoaderPath)) {
        fs.copyFileSync(testLoaderPath, testLoaderBackupPath);
    }

    // Copy plugins.default.json -> plugins.lite.json (for EE loader to compare against)
    fs.copyFileSync(defaultPluginsPath, pluginsLitePath);
    console.log('[test-config] Created plugins.lite.json from plugins.default.json');

    // Copy plugins.ee.json -> plugins.json (enable all plugins for the API)
    fs.copyFileSync(eePluginsPath, pluginsPath);
    console.log('[test-config] Using plugins.ee.json for enterprise tests');

    // Create EE test loader with correct paths for core repo
    // (The original script has paths relative to plugins repo, so we generate it here)
    const eeTestLoaderContent = `
// EE-only plugin test loader (generated by enterprise-plugins.js)
// Runs tests only for enterprise-exclusive plugins (not in plugins.default.json)
var pluginsLite = require("../../plugins/plugins.lite.json");
var pluginsAll = require("../../../plugins/plugins.ee.json");

console.log("Lite plugins:", pluginsLite.length);
console.log("All EE plugins:", pluginsAll.length);

if (pluginsAll.length > 0) {
    for (var i = 0, l = pluginsAll.length; i < l; i++) {
        if (pluginsLite.indexOf(pluginsAll[i]) === -1) {
            console.log("Running tests for EE plugin:", pluginsAll[i]);
            try {
                require("../../plugins/" + pluginsAll[i] + "/tests");
            }
            catch (ex) {
                console.log("No tests found for", pluginsAll[i], ":", ex.message);
            }
        }
    }
}
`;
    fs.writeFileSync(testLoaderPath, eeTestLoaderContent.trim());
    console.log('[test-config] Created EE-only test loader (runs only enterprise-exclusive plugins)');
}
else {
    console.warn('[test-config] Required files not found:');
    console.warn('  - plugins.ee.json:', fs.existsSync(eePluginsPath));
    console.warn('  - plugins.default.json:', fs.existsSync(defaultPluginsPath));
}

// Set plugin test credentials
process.env.COUNTLY_TEST_APP_ID = '58bf06bd6cba850047ac9f19';
process.env.COUNTLY_TEST_APP_KEY = 'b41e02136be60a58b9b7459ad89030537a58e099';
process.env.COUNTLY_TEST_API_KEY_ADMIN = 'e6bfab40a224d55a2f5d40c83abc7ed4';

module.exports = {
    bail: false, // Continue running after failures
    spec: [
        'test/1.frontend/0.load.db.js',
        'test/4.plugins/**/*.js',
        'test/5.cleanup/100.close.db.js'
    ],
    ignore: [
        '**/*.unit.js',
        '**/3.debug.js', // Interactive debug file - requires stdin
        '**/separation/**' // Separation tests close MongoDB connection prematurely
    ],
    require: ['test/configs/mocha/integration-hooks.js'],
    reporter: 'spec',
    timeout: 180000 // 3 minutes - beforeAll needs ~50s+ for service startup and 40s stabilization
};
