/**
 * Mocha config for lite plugin tests
 * Runs tests for CE plugins only (from plugins.default.json)
 * This matches CI behavior for lite-plugins tests
 */

const fs = require('fs');
const path = require('path');

// Setup NODE_PATH for symlinked plugins to find core modules
const corePath = path.resolve(__dirname, '../../..');
const nodeModulesPath = path.resolve(corePath, 'node_modules');
process.env.NODE_PATH = [nodeModulesPath, corePath, process.env.NODE_PATH].filter(Boolean).join(':');
require('module').Module._initPaths();

const pluginsDir = path.resolve(corePath, 'plugins');
const testPluginsDir = path.resolve(__dirname, '../../4.plugins');

// Source files
const defaultPluginsPath = path.resolve(pluginsDir, 'plugins.default.json');

// Destination files
const pluginsPath = path.resolve(pluginsDir, 'plugins.json');
const pluginsBackupPath = path.resolve(pluginsDir, 'plugins.json.test-backup');
const testLoaderPath = path.resolve(testPluginsDir, '1.plugin.tests.js');
const testLoaderBackupPath = path.resolve(testPluginsDir, '1.plugin.tests.js.backup');

// Use plugins.default.json for lite tests (CE plugins only)
if (fs.existsSync(defaultPluginsPath)) {
    // Backup current files
    if (fs.existsSync(pluginsPath)) {
        fs.copyFileSync(pluginsPath, pluginsBackupPath);
    }
    if (fs.existsSync(testLoaderPath)) {
        fs.copyFileSync(testLoaderPath, testLoaderBackupPath);
    }

    fs.copyFileSync(defaultPluginsPath, pluginsPath);
    console.log('[test-config] Using plugins.default.json for lite tests');

    // Create CE-only test loader (runs only CE plugins from plugins.default.json)
    const ceTestLoaderContent = `
// CE-only plugin test loader (generated by lite-plugins.js)
// Runs tests only for CE plugins (from plugins.default.json)
var pluginsCE = require("../../plugins/plugins.default.json");

console.log("CE plugins to test:", pluginsCE.length); 

if (pluginsCE.length > 0) {
    for (var i = 0, l = pluginsCE.length; i < l; i++) {
        console.log("Running tests for CE plugin:", pluginsCE[i]);
        try {
            require("../../plugins/" + pluginsCE[i] + "/tests");
        }
        catch (ex) {
            console.log("No tests found for", pluginsCE[i], ":", ex.message);
        }
    }
}
`;
    fs.writeFileSync(testLoaderPath, ceTestLoaderContent.trim());
    console.log('[test-config] Created CE-only test loader (runs only plugins.default.json plugins)');
}
else {
    console.warn('[test-config] plugins.default.json not found, using existing plugins.json');
}

// Set plugin test credentials
process.env.COUNTLY_TEST_APP_ID = '58bf06bd6cba850047ac9f19';
process.env.COUNTLY_TEST_APP_KEY = 'b41e02136be60a58b9b7459ad89030537a58e099';
process.env.COUNTLY_TEST_API_KEY_ADMIN = 'e6bfab40a224d55a2f5d40c83abc7ed4';

module.exports = {
    bail: false, // Continue running after failures
    spec: [
        'test/1.frontend/0.load.db.js',
        'test/4.plugins/**/*.js',
        'test/5.cleanup/100.close.db.js'
    ],
    ignore: [
        '**/*.unit.js',
        '**/3.debug.js', // Interactive debug file - requires stdin
        '**/separation/**' // Separation tests close MongoDB connection prematurely
    ],
    require: ['test/configs/mocha/integration-hooks.js'],
    reporter: 'spec',
    timeout: 180000 // 3 minutes - beforeAll needs ~50s+ for service startup and 40s stabilization
};
