apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-clickhouse-writer
  namespace: countly
  labels:
    app: countly-clickhouse-writer
    branch: newarchitecture
    component: clickhouse-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countly-clickhouse-writer
  template:
    metadata:
      labels:
        app: countly-clickhouse-writer
        branch: newarchitecture
        component: clickhouse-writer
    spec:
      serviceAccountName: default
      tolerations:
      - key: countly
        operator: Equal
        value: dedicated
        effect: NoSchedule
      containers:
      - name: countly-clickhouse-writer
        image: countly-unified
        imagePullPolicy: Always
        args: ["npm", "run", "start:clickhouse-writer"]
        
        # This service runs in API mode. It loads API-specific environment variables
        # (e.g., COUNTLY_CONFIG_API_*) in addition to global ones (COUNTLY_CONFIG__*).
        # Load all configuration from ConfigMaps and Secrets
        envFrom:
        - configMapRef:
            name: countly-config
        - configMapRef:
            name: countly-clickhouse-writer-config
        - configMapRef:
            name: observability-config-otlp
        - secretRef:
            name: common-config
        - secretRef:
            name: mongodb-config
        - secretRef:
            name: clickhouse-config
        
        # OpenTelemetry service-specific configuration
        env:
        - name: OTEL_SERVICE_NAME
          value: "countly-clickhouse-writer"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.namespace=countly,deployment.environment=production"
        
        resources:
          requests:
            memory: "5Gi"
            cpu: "2"
          limits:
            memory: "5Gi"
            cpu: "2"
        
        # ClickHouse Writer doesn't have HTTP endpoints, so we use exec probes
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'clickhouse/api/writer/index.js'"
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'clickhouse/api/writer/index.js'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'clickhouse/api/writer/index.js'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /opt/countly/log
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: countly-clickhouse-writer-hpa
  namespace: countly
  labels:
    app: countly-clickhouse-writer
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: countly-clickhouse-writer
  minReplicas: 1
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80