apiVersion: apps/v1
kind: Deployment
metadata:
  name: countly-jobserver
  namespace: countly
  labels:
    app: countly-jobserver
    branch: newarchitecture
    component: jobserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: countly-jobserver
  template:
    metadata:
      labels:
        app: countly-jobserver
        branch: newarchitecture
        component: jobserver
    spec:
      tolerations:
      - key: countly
        operator: Equal
        value: dedicated
        effect: NoSchedule
      containers:
      - name: countly-jobserver
        image: countly-unified
        imagePullPolicy: Always
        command: ["npm", "run", "start:jobserver"]
        
        # This service runs in API mode. It loads API-specific environment variables
        # (e.g., COUNTLY_CONFIG_API_*) in addition to global ones (COUNTLY_CONFIG__*).
        # Load all configuration from ConfigMaps and Secrets
        envFrom:
        - configMapRef:
            name: countly-config
        - configMapRef:
            name: countly-jobserver-config
        - secretRef:
            name: common-config
        - secretRef:
            name: mongodb-config
        - secretRef:
            name: clickhouse-config
        
        resources:
          requests:
            memory: "2.5Gi"
            cpu: "1"
          limits:
            memory: "2.5Gi"
            cpu: "1"
        
        # JobServer doesn't have HTTP endpoints, so we use exec probes
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'jobServer/index.js'"
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'jobServer/index.js'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep -v grep | grep 'jobServer/index.js'"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
        
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: logs
          mountPath: /opt/countly/log
      
      volumes:
      - name: tmp
        emptyDir: {}
      - name: logs
        emptyDir: {}
      
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: countly-jobserver-hpa
  namespace: countly
  labels:
    app: countly-jobserver
    component: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: countly-jobserver
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 85