apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: countly

resources:
# Custom headers for ingress
- custom-headers-configmap.yaml
# Countly resources
- namespace-and-secrets.yaml
- docker-registry-secret.yaml
- nginx-ingress-config.yaml
- countly-api.yaml
- countly-frontend.yaml
- countly-ingestor.yaml
- countly-aggregator.yaml
- countly-jobserver.yaml
- countly-clickhouse-writer.yaml
- countly-clickhouse-updater.yaml
- countly-ingress.yaml

labels:
- includeSelectors: true
  pairs:
    branch: newarchitecture

images:
- name: countly-unified
  newName: gcr.io/countly-dev-313620/newarch/countly-unified@sha256:b2ec10b6943c5c7dc726d41c37111c4a5a9df17d0119dd4fe3f496103b04ce93

# Generator options  
generatorOptions:
  labels:
    app: countly
    managed-by: kustomize

configMapGenerator:
- name: countly-config
  envs:
  - configs/common.env
- name: countly-api-config
  envs:
  - configs/api.env
- name: countly-frontend-config
  envs:
  - configs/frontend.env
- name: countly-ingestor-config
  envs:
  - configs/ingestor.env
- name: countly-aggregator-config
  envs:
  - configs/aggregator.env
- name: countly-jobserver-config
  envs:
  - configs/jobserver.env
- name: countly-clickhouse-writer-config
  envs:
  - configs/clickhouse-writer.env
- name: countly-clickhouse-updater-config
  envs:
  - configs/clickhouse-updater.env
- name: countly-mongodb-config
  envs:
  - configs/mongodb.env
- name: countly-clickhouse-config
  envs:
  - configs/clickhouse.env
- name: observability-config-otlp
  envs:
  - configs/countly-otlp.env

# Apply observability patches to deployments
patches:
- path: observability-patches.yaml

# Secrets are created manually to have full control over environment variable names
# uncomment for the first run
#secretGenerator:
# - name: common-config
#   behavior: create
#   envs:
#   - secrets/common.env
# - name: mongodb-config
#   behavior: create
#   envs:
#   - secrets/mongodb.env
# - name: clickhouse-config
#   behavior: create
#   envs:
#   - secrets/clickhouse.env
# - name: docker-pull-secret
#   type: kubernetes.io/dockerconfigjson
#   behavior: create
#   envs:
#   - secrets/docker-registry.env