apiVersion: v1
kind: Namespace
metadata:
  name: countly
  labels:
    name: countly
    purpose: countly-deployment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: countly
imagePullSecrets:
- name: docker-pull-secret