# This is a basic workflow to help you get started with Actions

name: PR

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master, next ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "lint"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Enable command line
        shell: bash
        run: sudo bash ./bin/scripts/detect.init.sh

      - name: Installing Countly
        shell: bash
        run: npm install
        
      - name: Enabling plugins
        shell: bash
        run: cp "./plugins/plugins.default.json" "./plugins/plugins.json"
              
      - name: ShellCheck
        shell: bash
        run: countly shellcheck
        
      - name: ESLint
        shell: bash
        run: npx eslint .
        
      - name: DistFiles
        shell: bash
        run: sudo countly task dist-all

  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Installing Countly
        shell: bash
        run: sudo bash ./bin/countly.install.sh
        
      - name: NodeJS version
        shell: bash
        run: nodejs --version
        
      - name: NPM version
        shell: bash
        run: npm --version
        
      - name: Mongo version
        shell: bash
        run: mongo --version
        
      - name: Wait for process
        shell: bash
        run: until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done
        
      - name: Tests
        shell: bash
        run: sudo countly test

      - name: Output API Logs
        if: ${{ always() }}
        run: cat log/countly-api.log
        
      - name: Output Dashboard Logs
        if: ${{ always() }}
        run: cat log/countly-dashboard.log
        
      - name: Output MongoDB Logs
        if: ${{ always() }}
        run: sudo cat /var/log/mongodb/mongod.log

  notify:
    runs-on: ubuntu-latest
    needs: [ lint, test ]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Send slack notification
        id: slack
        if: always()
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"url\":\"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\",\"status\":\"${{ job.status }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          
  test-docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: countly/countly-core:latest
    services:
      mongodb:
        image: mongo:4.4.12
        ports:
          - 27017:27017
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v2
        
      - name: Install git
        shell: bash
        run: apt-get -y install git
      
      - name: Starting process
        shell: bash
        run: /sbin/my_init &
        
      - name: Wait
        shell: bash
        run: sleep 100
        
      - name: Change directory
        shell: bash
        run: cd /opt/countly
        
      - name: NPM install
        shell: bash
        run: npm install
        
      - name: Tests
        shell: bash
        run: npx grunt mochaTest
