name: Release Notice
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  to_slack:
    runs-on: ubuntu-latest
    steps:
      # To check the github context
      - name: Dump Github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # This data can be any valid JSON from a previous step in the GitHub Action
          payload: |
            {
              "repository": "${{ github.repository }}",
              "tag_name": "${{ github.event.release.tag_name }}",
              "actor": "${{ github.actor }}",
              "body": ${{ toJSON(github.event.release.body) }},
              "html_url": "${{ github.event.release.html_url }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_RELEASE }}

  to_discord:
    runs-on: ubuntu-18.04
    name: Sends custom message
    steps:
      - name: Sending message
        uses: nhevia/discord-styled-releases@v1.2.3
        with:
          webhook_id: ${{ secrets.DISCORD_RELEASE_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_RELEASE_WEBHOOK_TOKEN }}
